KusionStack/kusion

go.mod
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/change.go
pkg/engine/operation/change_test.go
pkg/engine/operation/destory.go
pkg/engine/operation/destory_test.go
pkg/engine/operation/executable_node.go
pkg/engine/operation/operation.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/resource_node.go
pkg/engine/operation/resource_node_test.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/destroy/options_test.go

When `kusion apply` in preview stage, the previewed table not always the same.
- after pre-dependent nodes finished, these downEdges are executing in paralyzing, so we cannot ensure the key returned from resource_node.execute() are alway the same.
- map traversing(node id -> action), it is originally disordered.
- ignore concurrent execution of peer nodes
- save node id in sequence, keep order by traversing slice instead of map

bugfix: save node id in sequence when dag walking and node executed

---

go.mod
go.sum
pkg/kusionctl/cmd/cmd.go
pkg/kusionctl/cmd/deps/deps.go
pkg/kusionctl/cmd/deps/options.go

this PR solved issue #37 and provide a implementation by parsing the import statement in KCL files
support kusion deps subcommand. By kusion deps, we can list the upstream or the downstream files that have a direct/indirect dependency relationship with the focused files.
- command usage:
```
Show the KCL file dependency information in the current directory or the given workdir. By default, it will list all the
KCL files that are dependent on the given package path.
Options:
--direct='up': the inspect direct of the dependency information. Valid values: up, down. Defaults to up
--focus=[]: the paths to focus on to inspect. It cannot be empty and each path needs to be a valid relative path
from the workdir
--ignore=[]: the file paths to ignore when filtering the affected stacks/projects. …
```

Feature: support kusion deps subcommand

---

Dockerfile

Purpose:
* fix openssl error  
scene: https://github.com/KusionStack/konfig/runs/6500813553?check_suite_focus=true

chore: supplement libssl-dev dependency in Dockerfile

---

go.mod
go.sum

Purpose:
* bump yaml.v3 version from v3.0.0-20220512140231-539c8e751b99 to v3.0.0

chore: bump yaml version to v3.0.0

---

go.sum
pkg/engine/operation/change.go
pkg/engine/operation/change_test.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/resource_node.go
pkg/engine/operation/resource_node_test.go
pkg/engine/runtime/kubernetest_runtime.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/destroy/options_test.go

feat: 3 ways merge base on json merge patch

---

pkg/engine/operation/change.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/resource_node.go
pkg/engine/operation/types.go
pkg/engine/runtime/kubernetest_runtime.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/destroy/options_test.go

fix: https://github.com/KusionStack/kusion/issues/65
- runtime apply should differ create or patch, json merge patch cannot applied to an object which is not existed
- prompt cycle has a cancel condition, which is triggered every time
- refactor computing node's action logic
- use live state and plan state to make a diff report which is consistent with runtime logic

bugfix: runtime apply and detail prompt cancel unexpectly

---

pkg/scaffold/external_templates_test.go

UT `read from subdir` means to fetch 2 or more templates from `pkg/scaffold/internal`, now we have only one template, which is not compatible with more templates in the future.
The flaw of this one is pretty the same as above. Copy templates from src dir to target dir, now src dir contains only one, so it's not compatible with more templates as well.

fix unit test for pkg/scaffold/internal

---

pkg/kusionctl/cmd/init/options.go
pkg/scaffold/external_templates.go
pkg/scaffold/external_templates_test.go
pkg/scaffold/internal/deployment-single-stack/kusion.yaml
pkg/scaffold/project.go

ref: https://github.com/KusionStack/kusion/issues/72
This PR mainly to add missing field type for template render engine, especially composite type, eg: array, map and struct.
And I also rename struct field of ProjectTemplate, make it more accurate and consistency with custom params structure.

add new FiledType: MapField and AnyField to indicate map entry and interface{}

---

pkg/kusionctl/cmd/init/init.go
pkg/kusionctl/cmd/init/options.go
pkg/kusionctl/cmd/init/options_test.go
pkg/scaffold/external_templates.go
pkg/scaffold/external_templates_test.go
pkg/scaffold/project.go
pkg/scaffold/project_test.go

close: https://github.com/KusionStack/kusion/issues/72

feat: kusion init support custom params body in JSON string, replace default value in kusion.yaml of specified template

---

go.mod
go.sum
pkg/kusionctl/cmd/init/options.go
pkg/scaffold/internal_templates.go
pkg/scaffold/internal_templates_test.go
pkg/scaffold/templates.go
pkg/scaffold/templates_test.go

related: https://github.com/KusionStack/kusion/issues/72#issuecomment-1157618380
Refactor `CopyTemplateFiles()`(rename to `RenderLocalTemplate()`) to support different file system, not only local directory:
1. For the built-in templates, we must use the `go:embed` command, otherwise, we cannot compile it into binary, and we cannot access the built-in templates directory because of a relative path.
2. Render the template to the specified directory, the whole process is divided into 3 steps:
1. `ReadTemplate()`: read the local path to srcFS
2. `RenderFSTemplate()`: render srcFS to destFS
3. `WriteToDisk()`: write to disk
3. For third-party integration scenarios, you can choose one:
1. Local directory: `RenderLocalTemplate()`
2. Self-provided memory file system: `RenderFSTemplate()`
3. …

feat: refactor CopyTemplateFiles to support different file system

---

go.sum
pkg/engine/states/http_state.go
pkg/engine/states/http_state_test.go

pkg/engine/states
Add the HttpState backend to provide a generic way to manipulate State in third-party services
Test cases in pkg/engine/states/http_state_test.go
```release-note
Add HTTPState as a new StateStorage
```

State: add HTTPState as a new StateStorage

---

pkg/engine/operation/apply.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/parser/spec_parser.go
pkg/engine/operation/preview_test.go
pkg/engine/runtime/kubernetes_runtime.go
pkg/engine/runtime/runtime.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/destroy/options_test.go

pkg/engine/runtime
refactor engine/runtime and do not change any features
- combine Runtime interface request params and result params into Request struct and Response struct to make it easier to iterate in future
- add dryRun option in Runtime.Apply
```release-note
None
```

refactor Runtime interface

---

pkg/engine/runtime/kubernetes_runtime.go
pkg/engine/states/local/filesystem_state.go
pkg/engine/states/remote/db_state.go
pkg/util/yaml/yaml.go

- use ` gopkg.in/yaml.v3` instead of ` gopkg.in/yaml.v2`, and change the db_stage by the way
- runtime dry-run not cover `create` verb, add it

 bugfix: yaml.v2 unmarshal json content, make metadata type map[interface{}]interface{}

---

go.mod
go.sum
pkg/kusionctl/cmd/deps/deps_test.go
pkg/kusionctl/cmd/deps/options.go
pkg/kusionctl/cmd/deps/testdata/appops/projectA/base/base.k
pkg/kusionctl/cmd/deps/testdata/appops/projectA/dev/kcl.yaml
pkg/kusionctl/cmd/deps/testdata/appops/projectB/base/base.k
pkg/kusionctl/cmd/deps/testdata/appops/projectB/dev/kcl.yaml
pkg/kusionctl/cmd/deps/testdata/appops/projectC/dev/kcl.yaml
pkg/kusionctl/cmd/deps/testdata/appops/projectC/dev/main.k
pkg/kusionctl/cmd/deps/testdata/base/frontend/container/container.k
pkg/kusionctl/cmd/deps/testdata/base/frontend/container/container_port.k
pkg/kusionctl/cmd/deps/testdata/base/frontend/job/job.k
pkg/kusionctl/cmd/deps/testdata/base/frontend/server/server.k

- pkg/kusionctl/cmd/deps/options.go
- go.mod: In order to update the latest kclvm-go deps API, the kclvm-go version in go.mod is updated to v0.4.3-alpha.1
before the PR, the in-existing file paths as ```--focus``` option is not allowed in using the ```kusion deps``` command to find downstream stacks/projects and the in-existing file paths will cause an "invalid focus path" error.
This PR support deleted files in ```kusion deps --focus``` option, and slightly improves the performance of that command.
This PR adds some unit tests and benchmarks on the core logic about down stream stacks/projects analyzing.
This PR brings some reduction on memory usage result based on the testdata and brings about 50% time and memory consumption base on a 2000+ stacks Konfig repository.
benchstat result on …

support deleted files in kusion deps cmd

---

pkg/engine/operation/graph/resource_node.go
pkg/engine/runtime/kubernetes_runtime.go
pkg/engine/states/local/filesystem_state.go
pkg/engine/states/state.go

1. return Resource.Type and Resource.Extensions in K8s Runtime
2. fix filesystem_state createTime bug
pkg/engine/states/local
pkg/engine/runtime
1. return Resource.Type and Resource.Extensions in K8s Runtime
2. fix filesystem_state createTime bug
```release-note
None
```

Return Resource.Type and Resource.Extensions in K8s Runtime

---

pkg/scaffold/templates.go

wrong use `stack.yaml` as map key of Template.StackConfigs, stack directory name is correct.

bugfix: stack directory name is map key of Template.StacksConfig

---

pkg/compile/compile.go
pkg/compile/compile_test.go
pkg/compile/testdata/crd/foo.yaml
pkg/resources/crd/crd.go
pkg/resources/crd/crd_test.go
pkg/resources/crd/testdata/multi.yaml
pkg/resources/crd/testdata/one.yaml
pkg/resources/visitor.go

fix issue: https://github.com/KusionStack/kusion/issues/66
Support k8s CRD in `kusion apply` and `kusion destroy`:
**Precondition:** 
- CRD files are in YAML or JSON format, stored in `crd` directory under project path
**Operations:**
- Read all CRD files (`readCRDs()`) and append to compiled result (`appendCRDs()`)

feat: support k8s crd in kusion apply and kusion destroy

---

pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/preview_test.go

fix: https://github.com/KusionStack/kusion/issues/109
**Root Causes**
- `kusion apply` will build an acyclic graph which contains  only two kinds of action, `Update` and `Delete`, only `Update` nodes need to determine `Create` or `Update`
- Nodes of `Update` action, its state field is **plan state**; otherwise, node of `Delete` action, its state field is **prior state**
- For nodes of `Delete` action, wrongly used `node.state` as plan state in `execute()` func, so `Delete` turns to `Unchange`

bugfix: resource nodes of delete action don't need compute action type again

---

pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/models/operation_context.go

fix: https://github.com/KusionStack/kusion/issues/102
`Resource` is living in `Runtime`, but not applied by kusion, next time user use kusion to apply the same `Resource` but no changes, kusion should save it in `State`

bugfix: save unchanged but lived resource

---

pkg/kusionctl/cmd/apply/apply.go
pkg/kusionctl/cmd/compile/compile.go
pkg/kusionctl/cmd/destroy/destroy.go

fix: #110 
kusion compile flag,  `-D` use `pflag.StringSliceVarP()` to parse string slice arguments, according to the comments here:
https://github.com/spf13/pflag/blob/d5e0c0615acee7028e1e2740a11102313be88de1/string_slice.go#L99
```
compared to StringArray flags, StringSlice flags take comma-separated value as arguments and split them accordingly.
```
so, use `pflag.StringArrayVarP()` instead, will prevent pflag from truncating long string by comma.
After replace, the compiled result meets expectation:
```bash
./kusion compile a.k -D a='["x","y","z"]' -D b='{"key": False}'
```
output:
```yaml
a:
- x
- y
- z
b:
key: false
```

bugfix: invalid argument for "-D, --argument" flag: parse error, bare " in non-quoted-field

---

pkg/engine/states/backend.go
pkg/engine/states/state.go

pkg/engine/states/
```release-note
None
```

refactor backend

---

pkg/version/types.go
pkg/version/types_test.go

ref: https://semver.org/
```python
from packaging import version
print(version.parse("v0.3.22-2abnsx"))  # Invalid version: v0.3.22-2abnsx 
print(version.parse("v0.3.22.2abnsx"))  # Invalid version: v0.3.22.2abnsx
print(version.parse("v0.3.22+2abnsx")) # Valid version: 0.3.22+2abnsx
print(version.parse("v0.3.22-alpha.01-2abnsx")) # Invalid version: v0.3.22-alpha.01-2abnsx
print(version.parse("v0.3.22-alpha.01.2abnsx")) # Invalid version: v0.3.22-alpha.01.2abnsx
print(version.parse("v0.3.22-alpha.01+2abnsx")) # Valid version: 0.3.22a1+2abnsx 
print(version.parse("v0.3.22-beta.02-2abnsx")) # Invalid version: v0.3.22-beta.02-2abnsx
print(version.parse("v0.3.22-beta.02.2abnsx")) # Invalid version: v0.3.22-beta.02.2abnsx
print(version.parse("v0.3.22-beta.02+2abnsx")) # Valid version: …
```

chore: fix version format to match semantic versioning 2.0.0

---

pkg/kusionctl/cmd/apply/options.go

fix https://github.com/KusionStack/kusion/issues/129

bugfix: set progressbar width to 0 manually, pterm will use terminal width

---

pkg/engine/runtime/kubernetes_runtime.go

fix: https://github.com/KusionStack/kusion/issues/133
Kusion will try `ServerSideDryRun` first, if runtime doest not support `ServerSideDryRun`, kusion will fall back to `ClientSideDryRun`, user will not perceive it.

feat: kusion apply support ServerSide preview

---

pkg/engine/models/spec.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/models/change.go
pkg/engine/operation/models/change_test.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/preview.go
pkg/kusionctl/cmd/apply/apply.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/compile/options.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/preview/options.go
pkg/kusionctl/cmd/preview/options_test.go
pkg/kusionctl/cmd/preview/preview.go
pkg/kusionctl/cmd/preview/preview_test.go

close: #126 
- feat: cmd preview and apply support new flag '--ignore-fields'
- refactor: distinguish compile flags and options
- refactor: move preview logic from `cmd/apply` to `cmd/preview`
- refactor: delete `io.writer` from `func Preview()` and add to `func Summary()`

feat: cmd preview and apply support new flag '--ignore-fields'

---

go.sum
hack/run-e2e.sh

fix #158 
fix e2e test ginkgo version
```release-note
None
```

fix ginkgo version

---

pkg/kusionctl/cmd/apply/apply.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/preview/options.go
pkg/kusionctl/cmd/preview/options_test.go
pkg/kusionctl/cmd/preview/preview.go

1. move `--no-style` flag from `ApplyOptions` to `PreviewOptions`
2. default preview result is summary, `--detail` can output details

chore: refactor compile flags

---

pkg/engine/operation/watch.go
pkg/engine/operation/watch_test.go
pkg/engine/printers/table.go
pkg/engine/runtime/kubernetes_runtime.go
pkg/engine/runtime/runtime.go

close: https://github.com/KusionStack/kusion/issues/167
main changes:
1. relationships among resources, including ownerRef and selector
2. structured watch data, not flush screen with new message
3. table like UI, print each resource as table and render dynamically
sample:

feat: watch dependents and print them with new console UI

---

go.mod
go.sum
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/preview/options.go

apply and preview cmd
```release-note
support empty resource in stack in some circumstances
```

fix: empty resources in stack will generate panic

---

pkg/compile/compile.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/destroy/options_test.go
pkg/kusionctl/cmd/preview/options.go
pkg/kusionctl/cmd/preview/options_test.go
pkg/kusionctl/cmd/preview/preview.go

1. `kusion preview`: add new flag `--all`, combined with `--detail`, will directly print all diff details without interaction.
2. `kusion apply`: remove useless flag `OnlyPreview`, which is never used.
3. refactor func `CompileWithSpinner()`, make spinner style can be turn on/off by `--no-style`

chore: refactor preview flags

---

pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory.go
pkg/engine/operation/destory_test.go
pkg/engine/operation/graph/executable_node.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/models/action.go
pkg/engine/operation/models/change.go
pkg/engine/operation/models/change_test.go
pkg/engine/operation/models/doc.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/models/operation_type.go
pkg/engine/operation/parser/delete_resource_parser.go
pkg/engine/operation/parser/delete_resource_parser_test.go
pkg/engine/operation/parser/parser.go
pkg/engine/operation/parser/spec_parser.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/destroy/options_test.go
pkg/kusionctl/cmd/preview/options.go
pkg/kusionctl/cmd/preview/options_test.go

Pkg `operation` has two sub pkg, `models` and `types`, they are written for same usages, so merge them to one pkg.
For avoiding import path collision, takes `types` as the final choice.
This PR changes 20+ files, mostly changes are `import` path and format.

refactor: merge pkg operation/models to operation/types

---

.github/workflows/release.yaml
Dockerfile
Makefile
go.mod
go.sum

fix: #179 
feat: bump kclvm version and support kclvm windows artifact.
```release-note
None
```

feat: bump kclvm version and support kclvm windows artifact.

---

.github/workflows/e2e-test.yml
.github/workflows/release.yaml
.github/workflows/test.yaml
Dockerfile
Makefile
hack/run-e2e.sh

- there is no distinction between centos and ubuntu for kclvm
- no need to install kcl-go or kclvm once again, cause they are embebed in kclvm-go
- embeded kcl stuff will save in GOBIN

fix makefile

---

pkg/engine/runtime/terraform/tfops/workspace.go

pkg/engine/runtime/terraform/tfops/
```release-note
None
```

check if the provider hash or version has changed

---

.github/workflows/release.yaml
.gitignore
.goreleaser.yml
Dockerfile
pkg/version/.gitignore

close: https://github.com/KusionStack/kusion/issues/178
- correct goos and goarch combination
- release tarball and docker image by goreleaser
- rewrite dockerfile to support docker build and goreleaser build
- support brew install kusion

use goreleaser to release tarballs and docker image

---

.golangci.yml
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory.go
pkg/engine/operation/destory_test.go
pkg/engine/operation/diff.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/runtime/runtime.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/preview/options.go

add Stack in operation context and runtime interface for TF Runtime

add Stack in operation context and runtime interface

---

pkg/kusionctl/cmd/compile/options.go

close: #223
when compile KCL project, will default output to `ci-test/std.golden.yaml` when compile single KCL file, should default output to `stdout`

bugfix: no such file or directory for compile

---

pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory.go
pkg/engine/operation/destory_test.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/watch.go
pkg/engine/operation/watch_test.go
pkg/engine/runtime/init/init.go
pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply/options_test.go
pkg/kusionctl/cmd/cmd.go
pkg/kusionctl/cmd/destroy/options.go
pkg/kusionctl/cmd/destroy/options_test.go
pkg/kusionctl/cmd/preview/options.go
pkg/kusionctl/cmd/preview/options_test.go
pkg/kusionctl/cmd/util/helpers.go

upgrade all operations to support manipulating multi-runtime resources in one Stack. This commit consist of two major changes
1. update the Runtime field in Operation to RuntimeMap to contains multi-runtimes 
2. move Runtime initialization from cmd to engine because we can figure out all Runtime types in one Stack only if merging plan resources and prior resources together
#218 
cmd & engine
upgrade all operations to support manipulating multi-runtime resources in one Stack. This commit consist of two major changes
```release-note
Support hybrid-runtime resources operation like k8s and terraform in one Stack
```

Support hybrid-runtime resources operation like k8s and terraform in one Stack

---

pkg/engine/runtime/terraform/terraform_runtime.go
pkg/engine/runtime/terraform/terraform_runtime_test.go

Fix the error of writing and executing files in the workspace when the terraform runtime is executed concurrently

fix tf runtime concurrent execution

---

pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go

/kind feature
Fixes https://github.com/KusionStack/kusion/issues/241
Slice type passes tests, use recursive type assertion can do that.
`kind` can not be specified, because `ResourceNode` supports k8s and tf, `Type` field is used to differ them.
```release-note
enhancement: ignore field support slice type
```
```docs
None
```

enhancement: ignore field support slice type

---

pkg/engine/runtime/kubernetes/kubernetes_runtime.go
pkg/engine/runtime/kubernetes/kubernetes_runtime_test.go
pkg/engine/runtime/kubernetes/testdata/live_service_import_result.yaml

/kind feature
add normalizeService in k8s runtime
```release-note
normalize Service by delete clusterIP(s) when importing k8s resources
```
```docs
```

normalize the Service when importing in k8s runtime

---

.github/workflows/release.yaml
.github/workflows/test.yaml

/kind cleanup
```release-note
NONE
```
```docs
```

chore: use golangci-lint github action instead if manual download

---

pkg/engine/operation/watch.go
pkg/engine/printers/table.go

/kind feature
Fixes #239
```release-note
refactor: use reflect pkg to break the limit of for-range by dynamic select/case set
```
```docs
None
```

use reflect pkg to break the limit of for-range by dynamic select/case

---

pkg/cmd/compile/options.go
pkg/generator/kcl/kcl_generator.go

/kind refactor
/kind cleanup
refactor and cleanup the compile command to make it more general and readable
```release-note
```
```docs
```

refactor and cleanup the compile command

---

go.mod
go.sum
pkg/cmd/apply/options.go
pkg/cmd/apply/options_test.go
pkg/cmd/destroy/options_test.go
pkg/cmd/preview/options_test.go
pkg/engine/operation/watch.go
pkg/engine/operation/watch_test.go
pkg/engine/printers/table.go
pkg/engine/runtime/kubernetes/kubernetes_runtime.go
pkg/engine/runtime/runtime.go
pkg/engine/util.go
pkg/generator/kcl/util.go

/kind bug
- skip unsupported resources instead of returning error
- wait for the first watched obj if has dependent
- replace go module ref to ignore ASCII color codes
Fixes https://github.com/KusionStack/kusion/issues/253
```release-note
NONE
```
```docs
NONE
```

bugfix: kusion watch has no pod details

---

pkg/engine/operation/watch.go
pkg/engine/printers/convert.go
pkg/engine/printers/convertor/k8s_convertor.go
pkg/engine/printers/convertor/oam_convertor.go
pkg/engine/printers/generate.go
pkg/engine/printers/printer/k8s_printer.go
pkg/engine/printers/printer/oam_printer.go
pkg/engine/printers/printer/table_generator.go
pkg/engine/runtime/kubernetes/kubernetes_runtime.go

/kind bug
- avoid import cycle
Fixes #
- make Convert() and Generate() public
- avoid import cycle
```release-note
NONE
```
```docs
```

chore: refactor printers code structure

---

pkg/engine/runtime/terraform/terraform_runtime.go
pkg/engine/runtime/terraform/tfops/workspace.go

/kind bug
The original hcl lock file name is wrong, and I rename it to the right one
```release-note
None
```
```docs
None
```

Fix invalide hcl file name

---

pkg/engine/runtime/kubernetes/kubernetes_runtime.go

/kind feature
Normalize fields added by K8s that will cause a perpetual diff
Fixes #258 
```release-note
No
```
```docs
No
```

normalize fields added by K8s that will cause a perpetual diff

---

pkg/engine/operation/watch.go

/kind bug
TF resources not support watch, so ignore them, and not print details
Fixes #
```release-note
None
```
```docs
```

bugfix: ignore non-support TF resources

---

pkg/engine/operation/destory.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/preview_test.go
pkg/engine/runtime/terraform/terraform_runtime.go

/kind bug
kusion destroy TF resources, return success, but still there
Fixes https://github.com/KusionStack/kusion/issues/271
```release-note
NONE
```
```docs
```

bugfix: kusion destrory tf resources requires prior state and plan state

---

pkg/engine/runtime/terraform/terraform_runtime.go

/kind bug
we only need to refresh the tf.state files and return the latest resources state in this method.
Attributes in resources aren't necessary for the command `terraform apply -refresh-only` and will make errors if fields copied from kusion_state.json but illegal in .tf like the field `id`
Fixes #264 
```release-note
None
```
```docs
None
```

fix refreshing tf resources errors in read method

---

pkg/engine/operation/watch.go

/kind cleanup
Watching TF resources is not supported now. It is kind of our disadvantage, but we will record a promotion demo video recently. So I change the hint color to normal text to make it less attractive.
```release-note
none
```
```docs
none
```

make monitoring output less colourful

---

pkg/engine/runtime/terraform/tfops/workspace.go
pkg/engine/runtime/terraform/tfops/workspace_test.go
pkg/util/json/json.go

/kind feature
write tf.json and tf.state with pretty json to make them more user-friendly
Fixes #282 
None
```release-note
wirite `main.tf.json` and `terraform.tfstate` with pretty json to make them user friendly
```
```docs
none
```

write tf.json and tf.state with pretty json to make them more user-friendly

---

pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/preview_test.go
pkg/engine/runtime/terraform/terraform_runtime.go

/kind bug
Fix generating illegal tf.json
When a resource is deleted in Spec but exists in PriorState, this node should be regarded as a deleted node, and rn.state stores the PriorState. So we should set the planedState as nil

revert an old commit to fix generating illegal tf.json

---

pkg/cmd/destroy/options.go
pkg/engine/models/spec.go
pkg/engine/operation/destory.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/parser/delete_resource_parser.go
pkg/engine/operation/parser/parser.go
pkg/engine/operation/parser/spec_parser.go
pkg/engine/runtime/kubernetes/kubernetes_runtime.go

/kind feature
Only destroy resources Kusion already managed in kusion destroy
Fixes #299 
none
```release-note
Optimize `kusion destroy` behavior. The destroy operation will only delete resources already managed by Kusion
```
```docs
none
```

Only destroy resources Kusion already managed

---

pkg/engine/models/spec.go

/kind cleanup
delete redundant codes in spec.go
Fixes #
```release-note
```
```docs
```

delete redundant codes

---

pkg/cmd/deps/options.go

/kind update
Update: kusion deps: ignore all paths in --ignore option even if they appear in focus paths
The old behavior of `kusion deps` was: for entrance file list of each stack/project, if they contains the file that should be ignored(passed through `--ignore` option), then that ignored entrance file will not be regarded as that stack/project's upstream dependency.
That behavior was designed to avoid hotspot dependence like `https://github.com/KusionStack/konfig/blob/main/base/pkg/kusion_models/kube/render/render.k` which will involve almost all the frontend/backend files to a stack/project's upstream dependency.
Now there are scenarios that require ignoring paths even if they appear in focus paths.
```release-note
```
```docs
```

Update: kusion deps: ignore all paths in --ignore option even if they appear in focus paths

---

pkg/engine/runtime/terraform/terraform_runtime_test.go
pkg/engine/runtime/terraform/tfops/workspace_test.go

/kind cleanup
Fix failed TF UTs

fix TFRuntime uts

---

pkg/cmd/deps/options.go

/kind bug
Fixes #335 
```release-note
```
```docs
```

fix: kusion deps check if focus path under certain stack

---

pkg/cmd/init/init.go
pkg/cmd/init/options.go
pkg/cmd/init/options_test.go
pkg/scaffold/templates.go

feature
list init templates from local or online, support json format. Hence, user can parse the specific elements of the templates.
Fixes #265 
If the cmd failed, the output is not in json format, even if "--output=json" is specified.
```release-note
None
```
```docs
kusion init templates command helps you get the templates which are used to generate a scaffolding KCL project.
Here are the examples:
kusion init templates
kusion init templates https://github.com/<user>/<repo> --online=true --output=json
```

add "init templates" cmd, used to list templates in format

---

pkg/cmd/apply/options.go
pkg/cmd/destroy/options.go
pkg/status/status.go

close: https://github.com/KusionStack/kusion/issues/276

bugfix: dedup pint apply/destroy dag node executing error

---

pkg/cmd/init/init.go
pkg/cmd/init/options.go

feature
support specifying template when kusion init. By using flag --template-name, you can specify the template you want to use, prompt will not exist.
Fixes #265 
None
```release-note
None
```
```docs
None
```

support init with specified template 

---

pkg/cmd/compile/options.go
pkg/engine/kcl.go
pkg/generator/kcl/kcl_generator.go

close: https://github.com/KusionStack/kusion/issues/318

chore: use yaml.v2 to keep indent to 2 spaces

---

pkg/cmd/preview/options.go
pkg/cmd/preview/options_test.go
pkg/cmd/preview/preview.go
pkg/cmd/spec/generator.go
pkg/engine/operation/models/action.go
pkg/engine/operation/models/change.go
pkg/generator/generator.go

feature
when using cmd kusion preview, there is no way to get the pure preview result, cause there is prompt. Support --output json to print the preview result without any unnecessary prompt when succeeded.
Fixes #265 
```release-note
the output is json marshal of struct pkg/engine/operation/models.Changes
```
```docs
None
```

support kusion preview --ouput json

---

pkg/cmd/apply/options.go
pkg/engine/operation/apply.go

/kind bug
The ignore-fields flag is functional only during the preview stage and cannot be utilized during the apply stage.
Fixes #376
```release-note
Fix resources that have not changed are still being updated when using the apply command with the ignore-fields flag.
```
```docs
```

Fix resources that have not changed are still being updated when using the apply command with the ignore-fields flag

---

go.mod
go.sum
pkg/cmd/apply/options.go
pkg/cmd/compile/compile.go
pkg/cmd/compile/options.go
pkg/cmd/compile/options_test.go
pkg/cmd/preview/options.go
pkg/cmd/preview/options_test.go
pkg/cmd/spec/generator.go
pkg/generator/generator.go

/kind feature
This PR refines "no-style" command line option. 
Fixes #366 
This PR removes "no-prompt" command line option. 
```release-note
Add "no-style" option for kusion compile for better third-party integration while remove the "no-prompt" option. 
```
```docs
```

feat: refine no-style and remove no-prompt command option

---

pkg/engine/runtime/init/init.go

add more details when runtime init failed
Fixes #361 
```release-note
```
```docs
```

add more details when runtime init failed

---

.github/workflows/constraint.yaml
.github/workflows/test.yaml
.golangci.yml
commitlint.config.js

/kind ci
Kusion can follows the [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/) to improve better history information. More see:
https://github.com/KusionStack/karbour/blob/main/docs/contributor/code-contribute.md#commit-message-format
So, add ci checks such as commit lint, pull request title lint.
Screenshots:

ci: add ci checks such as commit lint, pull request title lint

---

pkg/cmd/preview/options_test.go

/kind cleanup
Use mock as the function name instead of monkey
Fixes #445

refactor: Use mock as the function name instead of monkey

---

pkg/cmd/check/check_test.go
pkg/cmd/compile/compile.go
pkg/cmd/compile/compile_test.go
pkg/cmd/compile/options.go
pkg/cmd/compile/options_test.go

/kind feature
Remove mandatory validation of settings.yaml during kusion compile.
Fixes #440

feat: remove mandatory validation of settings.yaml during kusion compile

---

pkg/cmd/spec/generator_test.go
pkg/generator/appconfiguration/generators/namespace_generator_test.go

/kind feature
add generator and namespace tests

test: add generator and namespace tests

---

pkg/generator/appconfiguration/app_configurations_generator.go
pkg/generator/appconfiguration/generators/util.go
pkg/generator/appconfiguration/generators/workload_service_generator.go

/kind refactor
Use generic optimization code:
* `ForeachOrderedApps / ForeachOrderedContainers => ForeachOrdered`
* `Int32Ptr => IntPtr`

refactor: use generic optimization code

---

pkg/models/appconfiguration/workload/common.go
pkg/models/appconfiguration/workload/job.go
pkg/models/appconfiguration/workload/service.go
pkg/models/appconfiguration/workload/workload.go
pkg/models/appconfiguration/workload/workload_test.go

/kind feature
Customize workload deserialization and serialization by type

feat: customize workload deserialization and serialization by type

---

pkg/generator/appconfiguration/generators/job_generator.go
pkg/generator/appconfiguration/generators/util.go
pkg/generator/appconfiguration/generators/workload_service_generator.go

/kind bug
- Fix missing labels and annotations injection logic
- Fix some typo

fix: missing labels and annotations injection logic

---

pkg/engine/printers/convert.go
pkg/engine/printers/convertor/kafed_convertor.go
pkg/engine/printers/convertor/kafed_convertor_test.go
pkg/engine/printers/generate.go
pkg/engine/printers/printer/kafed_printer.go
pkg/engine/printers/printer/kafed_printer_test.go
pkg/engine/printers/printer/oam_printer.go

/kind feature
feat: support watching the collaset
Fixes #438 
ignore some test files temporary due to the strange coveralls test coverage computing rules
```release-note
```
```docs
```

feat: support watching the collaset

---

pkg/generator/appconfiguration/generator/app_configurations_generator.go
pkg/generator/appconfiguration/generator/workload/job_generator_test.go
pkg/generator/appconfiguration/generator/workload/workload_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
pkg/generator/appconfiguration/util.go

/kind test
Complete workload unit tests

test: complete workload unit tests

---

pkg/generator/appconfiguration/generator/app_configurations_generator_test.go
pkg/generator/appconfiguration/util_test.go
pkg/models/appconfiguration/workload/workload.go
pkg/models/appconfiguration/workload/workload_test.go

/kind test
* Complete appconfiguartion model unit tests
* Fix wrong acceptor type of MarshalJSON and MarshalYAML

test: complete appconfiguartion model unit tests

---

pkg/generator/appconfiguration/generator/app_configurations_generator.go
pkg/generator/appconfiguration/generator/ordered_resources_generator.go
pkg/generator/appconfiguration/generator/ordered_resources_generator_test.go

/kind feature
Support default order of kubernetes resource.
```go
var defaultOrderedKinds = []string{
"Namespace",
"ResourceQuota",
"StorageClass",
"CustomResourceDefinition",
"ServiceAccount",
"PodSecurityPolicy",
"Role",
"ClusterRole",
"RoleBinding",
"ClusterRoleBinding",
"ConfigMap",
"Secret",
"Endpoints",
"Service",
"LimitRange",
"PriorityClass",
"PersistentVolume",
"PersistentVolumeClaim",
"Deployment",
"StatefulSet",
"CronJob",
"PodDisruptionBudget",
"MutatingWebhookConfiguration",
"ValidatingWebhookConfiguration",
}
```

feat: support default order of kubernetes resource

---

.github/workflows/test.yaml

/kind chore
upgrade the goveralls to v1.8.0

chore: upgrade the goveralls

---

pkg/models/appconfiguration/workload/container/container.go
pkg/models/appconfiguration/workload/container/container_test.go

/kind feature
update Container model add lifecycle types and encoding/decoding support.
Fixes #
```release-note
```
```docs
```

feat: add lifecycle type and encoding/decoding support

---

pkg/cmd/apply/options.go
pkg/cmd/check/check_test.go
pkg/cmd/compile/compile.go
pkg/cmd/compile/compile_test.go
pkg/cmd/compile/options.go
pkg/cmd/deps/deps_test.go
pkg/cmd/deps/options.go
pkg/cmd/destroy/options.go
pkg/cmd/diff/diff_test.go
pkg/cmd/diff/options.go
pkg/cmd/env/options.go
pkg/cmd/init/options.go
pkg/cmd/init/options_test.go
pkg/cmd/ls/options.go
pkg/cmd/ls/options_test.go
pkg/cmd/preview/options.go
pkg/cmd/preview/options_test.go
pkg/cmd/preview/preview.go
pkg/cmd/util/helpers.go
pkg/cmd/util/helpers_test.go
pkg/engine/operation/watch.go
pkg/generator/generator.go
pkg/generator/kcl/kcl_generator.go
pkg/generator/kcl/kcl_generator_test.go

/kind refactor
refactor: replace cmd arguments from string array to map and change struct names to follow go naming conventions
Fixes #
```release-note
```
```docs
```

refactor: replace cmd arguments from string array to map

---

pkg/generator/appconfiguration/generator/trait/ops_rule_generator.go
pkg/generator/appconfiguration/generator/trait/ops_rule_generator_test.go
pkg/generator/appconfiguration/generator/workload/service_generator.go
pkg/models/appconfiguration/appconfiguration.go
pkg/models/appconfiguration/appconfiguration_test.go
pkg/models/appconfiguration/trait/ops_rule.go
pkg/models/appconfiguration/workload/service.go

/kind feature
add a ruleset generator to support the maxavailable deploy strategy.
Fixes #469

feat: add a ruleset generator to support the maxavailable deploy strategy.

---

go.mod
go.sum
pkg/generator/appconfiguration/generator/workload/workload_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
pkg/models/appconfiguration/workload/common.go
pkg/util/net/parse.go
pkg/util/net/parse_test.go

/kind feature
update workload generator support probe&lifecycle attributes.
Fixes #
```release-note
```
```docs
```

feat: update workload generator support probe&lifecycle

---

pkg/generator/appconfiguration/generator/workload/job_generator.go
pkg/generator/appconfiguration/generator/workload/service_generator.go
pkg/generator/appconfiguration/generator/workload/service_generator_test.go
pkg/generator/appconfiguration/generator/workload/workload_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator_test.go

/kind feature
This PR adds support for creating files with ConfigMap in workload container. 
Fixes #379 
An example of creating files with ConfigMap in the container is shown below: 
```release-note
```
```docs
```

feat: support creating files with configmap in container

---

pkg/generator/appconfiguration/generator/workload/workload_generator.go

/kind bug
The URL in Probe model gets parsed and put into the corev1.Probe object.
The port gets parsed by `intstr.FromString(u.Port())` which ends up being a string in the rendered yaml:
This is rejected by Kubernetes because for a string port (as the port name) it expects at least one letter in it:
[`intstr.Parse()`](https://pkg.go.dev/k8s.io/apimachinery@v0.27.2/pkg/util/intstr#Parse) will attempt to convert the string to an int first which is what we want.
Fixes #
```release-note
```
```docs
```

fix: port in probe url now gets parsed properly

---

go.mod
go.sum
pkg/generator/appconfiguration/generator/app_configurations_generator.go
pkg/generator/appconfiguration/generator/monitoring_generator.go
pkg/generator/appconfiguration/generator/monitoring_generator_test.go
pkg/generator/appconfiguration/generator/workload/service_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
pkg/models/appconfiguration/appconfiguration.go
pkg/models/appconfiguration/monitoring/monitoring.go
pkg/projectstack/types.go

Fixes #
```release-note
NONE
```
```docs
Design doc: https://github.com/KusionStack/kusion/blob/main/docs/prometheus.md
```

feat: add Prometheus support

---

pkg/engine/operation/graph/resource_node.go

/kind bug
fix a npe panic when deleting a resource failed
Fixes #
```release-note
```
```docs
```

fix: a npe panic when deleting a resource failed

---

pkg/generator/appconfiguration/generator/app_configurations_generator.go
pkg/generator/appconfiguration/generator/workload/service_generator.go
pkg/generator/appconfiguration/generator/workload/service_generator_test.go
pkg/generator/appconfiguration/generator/workload/workload_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator_test.go

/kind feature
support configure the maxUnavailable field of a deployment

feat: support config maxunavaliable in deployment

---

pkg/generator/appconfiguration/generator/workload/workload_generator.go
pkg/generator/appconfiguration/generator/workload/workload_generator_test.go

/kind bug
set probe http action path to empty when url parse resolve localhost
Fixes #
```release-note
```
```docs
```

fix: set host to empty when url parse get localhost or 127.0.0.1

---

pkg/generator/appconfiguration/generator/app_configurations_generator.go
pkg/generator/appconfiguration/generator/trait/ops_rule_generator.go

/kind bug
don't generate a ruleset when the ops rule is empty
Fixes #
```release-note
```
```docs
```

fix: don't generate a ruleset when the ops rule is empty

---

pkg/generator/appconfiguration/generator/workload/network/ports_generator.go
pkg/generator/appconfiguration/generator/workload/network/ports_generator_test.go
pkg/generator/appconfiguration/generator/workload/service_generator_test.go

/kind bug
add a kusion-control label in svc labels
Fixes #
```release-note
```
```docs
```

fix: add a kusion-control label in svc labels

---

.github/workflows/e2e-test.yml
test/e2e/kusionctl_test.go

/kind bug
Fix wrong e2e ut for kusion deps and apply

fix: wrong e2e ut for kusion deps and apply

---

pkg/generator/appconfiguration/generator/accessories/database/aws_rds.go

/kind bug
This PR fixes some bugs for aws database generator. 
Fixes #540 
```release-note
```
```docs
```

fix: fix aws database generator

---

pkg/scaffold/templates.go
pkg/scaffold/templates_test.go

/kind bug
always delete external templates in init with the online flag
Fixes #368
```release-note
```
```docs
```

fix: delete external templates when init --online failed

---

pkg/cmd/cmd.go
pkg/cmd/cmd_test.go
pkg/cmd/version/options.go
pkg/cmd/version/version_test.go
pkg/version/scripts/gen/gen.go
pkg/version/types.go
pkg/version/types_test.go

Refs: #408
/kind feature
Fixes #408
```release-note
NONE
```
```docs
```

feat: remove dependency and v prefix of releaseVersion from version cmd output

---

pkg/generator/appconfiguration/generator/workload/secret/rand.go
pkg/generator/appconfiguration/generator/workload/secret/rand_test.go

/kind feature
add random string function for upcoming secret generator refact
Fixes #
```release-note
```
```docs
```

feat: add random string function for upcoming secret generator refact

---

pkg/engine/operation/watch.go

/kind bug
When I run `--watch` to monitor resource change, I got this error:
```bash
kusion apply --watch
✔︎  Generating Intent in the Stack dev...                                                                                                                                                                                           
Stack: dev  ID                                                          Action
* ├─       v1:Namespace:wordpress                                      Create
* ├─       v1:Secret:wordpress:wordpress-db-local-secret               Create
* ├─       v1:Secret:wordpress:wordpress-db                            Create
* ├─       v1:Service:wordpress:wordpress-dev-wordpress-private        Create
* ├─       v1:Service:wordpress:wordpress-db-local-service …
```

fix: stack nil pointer error

---

pkg/apis/project/types_test.go
pkg/cmd/build/builders/kcl/rest/rest_test.go
pkg/cmd/init/init_test.go
pkg/cmd/init/options_test.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory_test.go
pkg/engine/states/local/filesystem_state_test.go
pkg/engine/states/remote/db/db_state_test.go
pkg/engine/states/remote/oss/oss_state_test.go
pkg/engine/states/remote/s3/s3_state_test.go
pkg/scaffold/templates_test.go
pkg/util/gitutil/gitutil_test.go
pkg/util/io/dir_test.go
pkg/util/io/file_test.go
pkg/util/io/io_test.go
pkg/util/kfile/file_test.go
pkg/util/kube/config/config_test.go
pkg/version/types_test.go

…ARM64 compilation
chore: remove go build flags in the code that are not applicable for ARM64 compilation
/kind cleanup
Fixes #
```release-note
```
```docs
```

chore: remove go build flags in the code that are not applicable for ARM64 compilation

---

pkg/apis/workspace/backends.go
pkg/apis/workspace/modules.go
pkg/apis/workspace/runtimes.go
pkg/apis/workspace/util.go
pkg/apis/workspace/workspace.go

/kind feature
add domain model of workspace management.
Fixes #617 
For the `backend` config, should be completed later.

feat: add workspace domain model

---

pkg/apis/project/project.go
pkg/apis/project/project_test.go
pkg/apis/project/types.go
pkg/apis/project/types_test.go
pkg/cmd/apply/options_test.go
pkg/cmd/build/builders/appconfig_builder_test.go
pkg/cmd/build/options_test.go
pkg/cmd/build/util_test.go
pkg/cmd/destroy/options_test.go
pkg/cmd/preview/options_test.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory_test.go
pkg/engine/operation/models/change_test.go
pkg/engine/operation/preview_test.go
pkg/modules/generators/accessories/database/alicloud_rds_test.go
pkg/modules/generators/accessories/database/aws_rds_test.go
pkg/modules/generators/accessories/database/database_generator_test.go
pkg/modules/generators/accessories/database/local_database_test.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/modules/generators/monitoring/monitoring_generator.go
pkg/modules/generators/monitoring/monitoring_generator_test.go
pkg/modules/generators/trait/ops_rule_generator_test.go
pkg/modules/generators/workload/job_generator_test.go
pkg/modules/generators/workload/secret/secret_generator_test.go
pkg/modules/generators/workload/service_generator_test.go
pkg/modules/generators/workload/workload_generator_test.go
pkg/modules/patchers/monitoring/monitoring_patcher.go
pkg/modules/patchers/monitoring/monitoring_patcher_test.go

…ention
/kind cleanup
chore: rename ProjectConfiguration to Configuration to follow go convention
Fixes #
```release-note
```
```docs
```

chore: rename ProjectConfiguration to Configuration to follow go convention

---

pkg/apis/secrets/types.go
pkg/secrets/providers/hashivault/vault.go
pkg/secrets/providers/hashivault/vault_test.go

rename ExternalSecretRef key to name
Fixes #
```release-note
```
```docs
```

chore: rename ExternalSecretRef key to name

---

pkg/workspace/operator.go
pkg/workspace/operator_test.go
pkg/workspace/testdata/.workspace_for_list/dev.yaml
pkg/workspace/testdata/.workspace_for_list/pre.yaml
pkg/workspace/testdata/.workspace_for_list/prod.yaml
pkg/workspace/testdata/.workspaces/for_create_failure_ws.yaml
pkg/workspace/testdata/.workspaces/for_delete_ws.yaml
pkg/workspace/testdata/.workspaces/for_get_ws.yaml
pkg/workspace/testdata/.workspaces/for_update_ws.yaml
pkg/workspace/util.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go

/kind feature
Add workspace CURD operation
Fixes #622

feat: add workspace CRUD operations

---

pkg/apis/workspace/types.go
pkg/workspace/operator.go
pkg/workspace/operator_test.go
pkg/workspace/validation.go

…ce dir is not hidden folder
/kind feature
1. add CURD func by default workspace operator;
2. use inline for the `GenericObjectStorageConfig` for `OssConfig` and `S3Config`;
3. correct validation for `S3Config`.

feat: update workspace util func and fix known bug

---

pkg/apis/workspace/types.go
pkg/workspace/testdata/workspaces/for_delete_ws.yaml
pkg/workspace/testdata/workspaces/for_update_ws.yaml
pkg/workspace/util.go
pkg/workspace/util_test.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go

/kind feature
Update the struct of `TerraformConfig`, introduce type `ProviderConfig`.

refactor: update the struct of TerraformConfig

---

pkg/apis/workspace/types.go
pkg/cmd/build/builders/appconfig_builder_test.go
pkg/cmd/build/util.go
pkg/cmd/build/util_test.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/workspace/testdata/workspaces/for_delete_ws.yaml
pkg/workspace/testdata/workspaces/for_update_ws.yaml
pkg/workspace/util.go
pkg/workspace/util_test.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go
test/e2e/e2e_suite_test.go

/kind feature
Update the struct of ModuleConfig.

refactor: update the struct of ModuleConfig

---

pkg/apis/intent/resource.go
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/watch.go
pkg/engine/operation/watch_test.go
pkg/engine/runtime/init/init.go
pkg/engine/runtime/init/init_test.go
pkg/engine/runtime/kubernetes/kubeops/config.go
pkg/engine/runtime/kubernetes/kubeops/config_test.go
pkg/engine/runtime/kubernetes/kubernetes_runtime.go
pkg/engine/runtime/terraform/terraform_runtime.go

/kind feature
use kubeConfig in extensions to init kubernetes runtime.

feat: use kubeConfig in extensions to init kubernetes runtime

---

pkg/secrets/providers.go
pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
pkg/secrets/providers/hashivault/vault.go
pkg/secrets/providers/register/register.go
pkg/secrets/providers_test.go

update secret store provider implementation
Fixes #
```release-note
```
```docs
```

refactor: update secret store providers implementation

---

pkg/apis/stack/types.go
pkg/cmd/build/util_test.go
pkg/modules/generators/app_configurations_generator.go
pkg/modules/util.go
pkg/modules/util_test.go

/kind feature
Add kubeConfig from workspace in extensions when kusion build.
Fixes #655

feat: add kubeConfig from workspace in extensions when kusion build

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/namespace_generator.go
pkg/modules/generators/namespace_generator_test.go

/kind feature
support customize namespace name through workspace config
Fixes #
```release-note
```
```docs
```

feat: support customize namespace through workspace config

---

pkg/modules/generators/workload/secret/secret_generator.go

secret generator add more comments
Fixes #
```release-note
```
```docs
```

chore: secret generator add more comments

---

pkg/modules/generators/workload/service_generator.go
pkg/modules/util.go
pkg/workspace/util.go
pkg/workspace/util_test.go

/kind feature
add func of getting specified type from workspace genericConfig.

feat: add func of getting specified type from workspace genericConfig

---

Dockerfile
Dockerfile_kusionctl
pkg/util/kfile/file.go
pkg/util/kfile/file_test.go

/kind bug
Use the value of env `KUSION_HOME` instead of `KUSION_PATH` as the path to store kusion data, cause the former is `$HOME/.kusion` and the latter is `$HOME/.kusion/bin`. This change happens when changing the catalog of kusion package.

fix: misuse of env KUSION_PATH

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/workload/job_generator.go
pkg/modules/generators/workload/job_generator_test.go
pkg/modules/generators/workload/service_generator.go
pkg/modules/generators/workload/service_generator_test.go
pkg/modules/generators/workload/workload_generator.go
pkg/modules/generators/workload/workload_generator_test.go
pkg/modules/inputs/workload/common.go
pkg/modules/inputs/workload/job.go
pkg/modules/inputs/workload/service.go
pkg/workspace/util.go

/kind feature
Use workspace config when build service and job.
Fixes #666

feat: use workspace config when build service and job

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/trait/ops_rule_generator.go
pkg/modules/generators/trait/ops_rule_generator_test.go
pkg/modules/inputs/trait/ops_rule.go
pkg/modules/patchers/trait/ops_rule_patcher.go
pkg/modules/patchers/trait/ops_rule_patcher_test.go
pkg/modules/util.go

/kind feature
feat: opsRule supports workspace config
Fixes #
```release-note
```
```docs
```

feat: opsRule supports workspace config

---

pkg/cmd/cmd.go
pkg/cmd/workspace/cmd.go
pkg/cmd/workspace/cmd_test.go
pkg/cmd/workspace/create/cmd.go
pkg/cmd/workspace/create/cmd_test.go
pkg/cmd/workspace/create/options.go
pkg/cmd/workspace/create/options_test.go
pkg/cmd/workspace/del/cmd.go
pkg/cmd/workspace/del/cmd_test.go
pkg/cmd/workspace/del/options.go
pkg/cmd/workspace/del/options_test.go
pkg/cmd/workspace/list/cmd.go
pkg/cmd/workspace/list/cmd_test.go
pkg/cmd/workspace/show/cmd.go
pkg/cmd/workspace/show/cmd_test.go
pkg/cmd/workspace/show/options.go
pkg/cmd/workspace/show/options_test.go
pkg/cmd/workspace/update/cmd.go
pkg/cmd/workspace/update/cmd_test.go
pkg/cmd/workspace/update/options.go
pkg/cmd/workspace/update/options_test.go
pkg/cmd/workspace/util/testdata/invalid_ws.yaml
pkg/cmd/workspace/util/testdata/valid_ws.yaml
pkg/cmd/workspace/util/util.go
pkg/cmd/workspace/util/util_test.go
pkg/workspace/operator.go
pkg/workspace/operator_test.go
pkg/workspace/util.go

/kind feature
add workspace cli
Fixes #604

feat: add workspace cli

---

go.mod
pkg/cmd/build/builders/appconfig_builder_test.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/modules/generators/workload/network/ports_generator.go
pkg/modules/generators/workload/network/ports_generator_test.go
pkg/modules/generators/workload/service_generator.go
pkg/modules/generators/workload/service_generator_test.go
pkg/modules/generators/workload/workload_generator_test.go
pkg/modules/inputs/workload/network/port.go

/kind feature
refactor module port with config from workspace
Fixes #683

feat: refactor module port with config from workspace

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/workload/secret/secret_generator.go
pkg/modules/generators/workload/secret/secret_generator_test.go
pkg/modules/inputs/workload/secret.go
pkg/modules/interfaces.go
pkg/secrets/providers.go
pkg/secrets/providers/register/register.go

/kind feature
secret generator support external secret type
Fixes #
```release-note
```
```docs
```

feat: secret generator support external secret type

---

pkg/modules/generators/accessories/mysql/alicloud_rds.go
pkg/modules/generators/accessories/mysql/aws_rds.go
pkg/modules/generators/accessories/mysql/mysql_generator.go
pkg/modules/generators/accessories/postgres/alicloud_rds.go
pkg/modules/generators/accessories/postgres/aws_rds.go
pkg/modules/generators/accessories/postgres/postgres_generator.go
pkg/modules/inputs/provider.go
pkg/modules/inputs/provider_test.go

/kind bug
This PR fixes some issues about the database generator. 
Fixes #
```release-note
```
```docs
```

fix: fix some issues about database generator

---

README-zh.md
README.md

Fixes #
```release-note
```
```docs
```

docs: fix broken links

---

pkg/scaffold/templates.go

/kind bug
fix the bug of gitutil.GitCloneOrPull which generates the unexpected.git directory
Fixes #757 
Why using removing dirs is explained in Fixes #757

fix: the bug of unexpected.git directory

---

pkg/engine/runtime/kubernetes/kubernetes_runtime.go

/kind feature
This PR deletes server-side fields in Kubernetes runtime for a more precise and clean resource object. 
- Before: 
- After: 
Fixes #705 
```release-note
```
```docs
```

feat: delete server side fields in kubernetes runtime

---

pkg/cmd/cmd.go

/kind bug
This PR adds `options` sub-cmd for kusion root command and fix the wrong `--help` info. 
For example, below is the previous `--help` info of `kusion init`: 
And this is the result after the bug fix: 
Fixes #772 
```release-note
```
```docs
```

fix: add options sub-cmd for kusion

---

pkg/engine/runtime/kubernetes/kubernetes_runtime.go

/kind bug
This PR fixes the unspecified namespace failure for K8s resources. Kusion will now first validate the intent resource id and patch the `default` namespace for Kubernetes namespaced resources without specified namespace field. 
Fixes #411 
```release-note
```
```docs
```

fix: unspecified namespace failure for k8s resources

---

pkg/cmd/generate/run/fake/fake.go
pkg/cmd/generate/run/run.go
pkg/cmd/generate/run/run_test.go
pkg/cmd/generate/run/testdata/base/base.k
pkg/cmd/generate/run/testdata/prod/kcl.mod
pkg/cmd/generate/run/testdata/prod/main.k
pkg/cmd/generate/run/testdata/prod/stack.yaml
pkg/cmd/generate/run/testdata/project.yaml

/kind feature
add code runner to execute configuration code
Fixes #
```release-note
```
```docs
```

feat: add code runner for configuration code execution

---

pkg/cmd/util/resource/crd/multi_crd.yaml
pkg/cmd/util/resource/crd/webapp_crd.yaml
pkg/cmd/util/resource/visitor.go
pkg/cmd/util/resource/visitor_test.go

/kind feature
add crd resource visitor util
Fixes #
```release-note
```
```docs
```

feat: add crd resource visitor util

---

third_party/dyff/output_human.go
third_party/term/term.go

/kind bug
Fix term.GetTerminalWidth failed on windows 
Fixes #534

fix: term.GetTerminalWidth failed on windows

---

pkg/cmd/build/builders/kcl/kcl_builder.go
pkg/cmd/workspace/util/util_test.go
pkg/engine/backend/config.go
pkg/engine/backend/util_test.go
pkg/engine/states/local/filesystem_state.go
pkg/engine/states/local/filesystem_state_test.go
pkg/util/kfile/file.go
pkg/workspace/operator.go
pkg/workspace/operator_test.go

/kind bug
Provide correct path operation under windows. 
Fixes #815

fix: use package path/filepath instead of path to support windows

---

pkg/version/types.go

/kind bug
no assignment of releaseVersion when version in buildInfo is empty
Fixes #818

fix: no assignment of releaseVersion when version in buildInfo is empty

---

docs/design/kusion_module/kusion_modules.md

Fixes #
```release-note
```
```docs
```

docs: add module versions in the app config model and fix some typos

---

pkg/apis/core/v1/workspace.go
pkg/cmd/build/builders/appconfig_builder_test.go
pkg/cmd/build/util_test.go
pkg/engine/backend/config.go
pkg/engine/backend/config_test.go
pkg/engine/backend/init/init.go
pkg/engine/backend/options.go
pkg/engine/backend/options_test.go
pkg/engine/backend/util.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/workspace/util.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go

Fixes #
```release-note
```
```docs
```

feat: rename backend related configs in workspace to deprecated

---

pkg/apis/core/v1/appconfiguration.go
pkg/modules/proto/module.pb.go
pkg/modules/proto/module.proto

Fixes #
```release-note
```
```docs
```

feat: update module grpc interface

---

pkg/apis/core/v1/config.go
pkg/backend/storages/completion.go
pkg/backend/storages/completion_test.go
pkg/backend/storages/validation.go
pkg/backend/storages/validation_test.go

Fixes #
```release-note
```
```docs
```

feat: add backend config completion and validation funcs

---

go.mod
go.sum
pkg/backend/storages/local.go
pkg/backend/storages/local_test.go
pkg/backend/storages/mysql.go
pkg/backend/storages/mysql_test.go
pkg/backend/storages/oss.go
pkg/backend/storages/oss_test.go
pkg/backend/storages/s3.go
pkg/backend/storages/s3_test.go
pkg/backend/storages/validation_test.go

Fixes #
```release-note
```
```docs
```

feat: add backend storage local, mysql, oss, s3

---

pkg/config/operator.go
pkg/config/operator_test.go
pkg/config/registry.go
pkg/config/testdata/config_for_read.yaml
pkg/config/util_test.go
pkg/config/validation.go
pkg/config/validation_test.go

Fixes #
```release-note
```
```docs
```

chore: use validation from backend config and tidy package config

---

pkg/backend/backend.go
pkg/backend/backend_test.go
pkg/backend/storages/completion_test.go
pkg/backend/storages/local.go

Fixes #
```release-note
```
```docs
```

feat: add backend definition and new function

---

go.mod
pkg/modules/generators/workload/workload_generator.go
pkg/modules/generators/workload/workload_generator_test.go

/kind feature
workload generator support create contentFrom based file
Fixes #673 
```release-note
```
```docs
```

feat: workload generator support create contentFrom based file

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/interfaces.go

Fixes #
```release-note
```
```docs
```

feat: add context in module interface

---

pkg/modules/generators/workload/workload_generator.go
pkg/modules/generators/workload/workload_generator_test.go

/kind feature
add container dirs implementation
Fixes #674 
```release-note
```
```docs
```

feat: workload generator add container dirs implementation

---

pkg/apis/core/v1/state.go
pkg/engine/operation/models/operation_context.go
pkg/engine/state/storages/local.go
pkg/engine/state/storages/local_test.go
pkg/engine/state/storages/mysql.go
pkg/engine/state/storages/mysql_test.go
pkg/engine/state/storages/oss.go
pkg/engine/state/storages/oss_test.go
pkg/engine/state/storages/s3.go
pkg/engine/state/storages/s3_test.go
pkg/engine/state/storages/util.go

Fixes #
```release-note
```
```docs
```

feat: add state storage implementation: local, oss, s3, mysql

---

docs/design/kusion_module/kusion_modules.md
pkg/apis/core/v1/resource.go

/kind feature
This PR updates the patcher definition of the environment variables. 
Fixes #
```release-note
```
```docs
```

feat: update env patcher

---

pkg/backend/backend.go
pkg/backend/backend_test.go
pkg/backend/storages/completion.go
pkg/backend/storages/completion_test.go
pkg/backend/storages/local.go
pkg/backend/storages/local_test.go
pkg/backend/storages/mysql.go
pkg/backend/storages/mysql_test.go
pkg/backend/storages/oss.go
pkg/backend/storages/oss_test.go
pkg/backend/storages/s3.go
pkg/backend/storages/s3_test.go
pkg/engine/state/storages/util.go

Fixes #
```release-note
```
```docs
```

feat: add function StateStorage in backend, and implement it

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/modules/plugin.go

…rence them later on.
/kind feature
prepend patch env to existing env slices so developers can reference them later on.
Fixes #
```release-note
```
```docs
```

feat:  prepend patch env to existing env slices so developers can reference them later on

---

pkg/backend/backend.go
pkg/backend/storages/local.go
pkg/backend/storages/local_test.go
pkg/backend/storages/mysql.go
pkg/backend/storages/mysql_test.go
pkg/backend/storages/oss.go
pkg/backend/storages/oss_test.go
pkg/backend/storages/s3.go
pkg/backend/storages/s3_test.go
pkg/workspace/storages/util.go

Fixes #
```release-note
```
```docs
```

feat: add function workspaceStorage in interface backend, and implement it in local/mysql/oss/s3

---

pkg/backend/backend.go
pkg/workspace/storage.go
pkg/workspace/storages/local.go
pkg/workspace/storages/local_test.go
pkg/workspace/storages/mysql.go
pkg/workspace/storages/oss.go
pkg/workspace/storages/oss_test.go
pkg/workspace/storages/s3.go
pkg/workspace/storages/s3_test.go
pkg/workspace/storages/util.go

Fixes #
```release-note
```
```docs
```

feat: update the workspace storage definition and implementation

---

pkg/cmd/mod/mod.go
pkg/cmd/mod/mod_init.go
pkg/cmd/mod/mod_init_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat: support command `mod init`

---

pkg/cmd/workspace/create/cmd.go
pkg/cmd/workspace/create/options.go
pkg/cmd/workspace/create/options_test.go
pkg/cmd/workspace/del/cmd.go
pkg/cmd/workspace/del/options.go
pkg/cmd/workspace/del/options_test.go
pkg/cmd/workspace/list/cmd.go
pkg/cmd/workspace/list/cmd_test.go
pkg/cmd/workspace/list/options.go
pkg/cmd/workspace/list/options_test.go
pkg/cmd/workspace/show/cmd.go
pkg/cmd/workspace/show/options.go
pkg/cmd/workspace/show/options_test.go
pkg/cmd/workspace/update/cmd.go
pkg/cmd/workspace/update/options.go
pkg/cmd/workspace/update/options_test.go
pkg/cmd/workspace/util/util.go

Fixes #
```release-note
```
```docs
```

feat: update workspace cmds, add backend and current flags

---

pkg/cmd/workspace/cmd.go
pkg/cmd/workspace/switch/cmd.go
pkg/cmd/workspace/switch/cmd_test.go
pkg/cmd/workspace/switch/options.go
pkg/cmd/workspace/switch/options_test.go

Fixes #
```release-note
```
```docs
```

feat: add workspace switch cmd

---

pkg/modules/generators/app_configurations_generator_test.go
pkg/modules/plugin.go

Fixes #
```release-note
```
```docs
```

fix: npe when killing plugin client

---

pkg/log/log.go
pkg/log/types.go
pkg/log/zap.go
pkg/modules/plugin.go

/kind feature
feat: separate module logs into different files
Fixes #939 
```release-note
```
```docs
```

feat: separate module logs into different files

---

pkg/backend/backend.go
pkg/backend/storages/local.go
pkg/backend/storages/mysql.go
pkg/backend/storages/oss.go
pkg/backend/storages/s3.go
pkg/cmd/generate/generate.go
pkg/cmd/generate/generator/generator.go
pkg/engine/spec/storage.go
pkg/engine/spec/storages/local.go
pkg/engine/spec/storages/oss.go
pkg/engine/spec/storages/s3.go
pkg/engine/spec/storages/util.go
pkg/scaffold/quickstart/dev/kcl.mod

/kind feature
add spec storage implementation
Fixes #
```release-note
```
```docs
```

feat: add spec storage and integrate with generate cmd

---

pkg/modules/generators/app_configurations_generator.go

/kind feature
This updates the use of the yaml package in app_configurations_generator, unmarshaling `Workload` with **yaml.v2** and unmarshaling other generator request attributes with **yaml.v3**. 
Fixes #940 
```release-note
```
```docs
```

feat: update yaml package for appconfiguration generator

---

kusion.go
pkg/cmd/apply/options.go
pkg/cmd/destroy/options.go
pkg/engine/operation/models/change.go

/kind feature
This PR refines the cmd cli interactive output. 
Fixes #824 
```release-note
```
```docs
```

feat: refine cmd cli interactive output

---

docs/design/kusion_module/kusion_modules.md
pkg/apis/core/v1/appconfiguration.go
pkg/modules/proto/module.pb.go
pkg/modules/proto/module.proto

Fixes #
```release-note
```
```docs
```

docs: update the module design doc

---

pkg/cmd/init/init.go
pkg/cmd/init/options.go
pkg/cmd/init/options_test.go

/kind feature
Fixes #344 
```release-note
NONE
```
```docs
```

feat: add flag to init cmd to specify output file path

---

pkg/apis/core/v1/config.go
pkg/backend/backend.go
pkg/backend/backend_test.go
pkg/config/operator.go
pkg/config/operator_test.go
pkg/config/registry.go
pkg/config/testdata/config.yaml
pkg/config/util.go
pkg/config/util_test.go
pkg/config/validation.go
pkg/config/validation_test.go

Fixes #
```release-note
```
```docs
```

feat: add default backend in the configuration file

---

pkg/cmd/mod/mod_init.go
pkg/modules/generators/workload/workload_generator.go
pkg/modules/plugin.go

Fixes #
```release-note
```
```docs
```

fix: replace path.join with filepath.join

---

pkg/apis/api.kusion.io/group.go
pkg/apis/api.kusion.io/v1/resource.go
pkg/apis/api.kusion.io/v1/types.go
pkg/apis/internal.kusion.io/group.go
pkg/apis/internal.kusion.io/v1/marshal.go
pkg/apis/internal.kusion.io/v1/marshal_test.go
pkg/apis/internal.kusion.io/v1/types.go
pkg/apis/internal.kusion.io/v1/unmarshal.go
pkg/apis/internal.kusion.io/v1/unmarshal_test.go

update api package for enhanced maintainability
Fixes #
```release-note
```
```docs
```

refactor: update api package for enhanced maintainability

---

pkg/apis/api.kusion.io/v1/types.go
pkg/cmd/destroy/options.go
pkg/cmd/destroy/options_test.go
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory_test.go
pkg/engine/operation/diff.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/runtime/terraform/tfops/state.go
pkg/engine/runtime/terraform/tfops/workspace.go
pkg/engine/state/storage.go
pkg/engine/state/storages/local.go
pkg/engine/state/storages/local_test.go
pkg/engine/state/storages/mysql.go
pkg/engine/state/storages/mysql_test.go
pkg/engine/state/storages/oss.go
pkg/engine/state/storages/oss_test.go
pkg/engine/state/storages/s3.go
pkg/engine/state/storages/s3_test.go

Fixes #
```release-note
```
```docs
```

refactor: sign state to deprecated state

---

pkg/cmd/cmd.go
pkg/cmd/generate/generate.go

/kind feature
generate cmd use the terminal ui framework
Fixes #
```release-note
```
```docs
```

feat: generate cmd use terminal ui framework

---

pkg/cmd/mod/mod_push.go
pkg/oci/client/client.go
pkg/oci/client/push.go
pkg/oci/metadata/metadata.go

/kind feature
support os arch in mod push and ignore .git in the OCI artifact
Fixes #1014
```release-note
```
```docs
```

feat: support os arch in mod push and ignore .git in the OCI artifact

---

pkg/backend/backend.go
pkg/backend/storages/local.go
pkg/backend/storages/local_test.go
pkg/backend/storages/mysql.go
pkg/backend/storages/mysql_test.go
pkg/backend/storages/oss.go
pkg/backend/storages/oss_test.go
pkg/backend/storages/s3.go
pkg/backend/storages/s3_test.go
pkg/cmd/apply/apply.go
pkg/cmd/destroy/destroy.go
pkg/cmd/destroy/destroy_test.go
pkg/cmd/preview/preview.go
pkg/engine/state/storages/mysql.go
pkg/engine/state/storages/mysql_test.go
pkg/engine/state/storages/util.go

Fixes #
```release-note
```
```docs
```

feat: update state storage which is identified by project and workspace

---

pkg/cmd/generate/generate.go

/kind bug
Fix unexpected spec output format in byte slice.

fix: unexpected output in format byte slice

---

pkg/cmd/mod/mod_push.go
pkg/oci/client/push.go

https://github.com/opencontainers/image-spec/blob/main/image-index.md
/kind feature
group multiple os arch modules by image index
```release-note
```
```docs
```

feat: group multiple os arch modules by image index

---

pkg/cmd/meta/meta.go

/kind cleanup
delete application field from meta
Fixes #
```release-note
```
```docs
```

chore: delete application field from Meta

---

go.mod
pkg/cmd/cmd.go
pkg/cmd/project/cmd.go
pkg/cmd/project/cmd_test.go
pkg/cmd/project/create/cmd.go
pkg/cmd/project/create/cmd_test.go
pkg/cmd/project/create/options.go
pkg/cmd/project/create/options_test.go
pkg/cmd/project/util/util.go
pkg/cmd/project/util/util_test.go
pkg/cmd/stack/cmd.go
pkg/cmd/stack/cmd_test.go
pkg/cmd/stack/create/cmd.go
pkg/cmd/stack/create/cmd_test.go
pkg/cmd/stack/create/options.go
pkg/cmd/stack/create/options_test.go
pkg/cmd/stack/util/util.go
pkg/cmd/stack/util/util_test.go

/kind feature
This PR adds support for sub command of `kusion project` and `kusion stack`. 
Fixes #782 
```release-note
```
```docs
```

feat: support sub cmd of kusion project and stack

---

pkg/apis/api.kusion.io/v1/types.go
pkg/cmd/workspace/util/testdata/valid_ws.yaml
pkg/modules/generators/app_configurations_generator_test.go
pkg/workspace/storages/local_test.go
pkg/workspace/storages/testdata/for_delete_workspaces/dev.yaml
pkg/workspace/storages/testdata/for_set_current_workspaces/dev.yaml
pkg/workspace/storages/testdata/workspaces/dev.yaml
pkg/workspace/storages/testdata/workspaces/prod.yaml
pkg/workspace/util.go
pkg/workspace/util_test.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go

Fixes #
```release-note
```
```docs
```

feat: update workspace mod definition

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/modules/plugin.go

Fixes #
```release-note
```
```docs
```

feat: export some plugin functions

---

pkg/cmd/destroy/destroy.go

/kind feature
This PR updates the progress bar of the `kusion destroy` cmd. 
Fixes #
```release-note
```
```docs
```

feat: update kusion destroy progressbar

---

pkg/cmd/workspace/update/options.go

/kind bug
This PR fixes the bug of `kusion workspace update` not supporting current workspace if not specified. 
Fixes #1073 
```release-note
```
```docs
```

fix: workspace update defaults to use current workspace

---

pkg/cmd/meta/meta.go

/kind bug
This PR adds `--workdir` to meta flags of Kusion CLI. 
Fixes #1064 
```release-note
```
```docs
```

fix: add workdir to meta flag of kusion cli

---

pkg/engine/api/generate/generator/generator.go
pkg/engine/api/generate/run/run.go

Fixes #
```release-note
```
```docs
```

feat: download kusion modules with current os arch filter

---

test/e2e/kusionctl_test.go

/kind test
This PR restores the e2e tests of Kusion CLI after updating the Kusion modules. 
Fixes #
```release-note
```
```docs
```

test: restore e2e tests after updating modules

---

hack/gen-docs/main.go
pkg/cmd/apply/apply.go
pkg/cmd/cmd.go
pkg/cmd/generate/generate.go
pkg/cmd/mod/mod.go
pkg/cmd/mod/mod_push.go
pkg/cmd/preview/preview.go

/kind feature
This PR updates the `--help` descriptions of the Kusion CLI. 
Fixes #811 
```release-note
```
```docs
```

feat: update kusion cli descriptions

---

pkg/apis/api.kusion.io/v1/types.go

Fixes #
```release-note
```
```docs
```

feat: add Release type which is triggered by kusion apply

---

pkg/engine/api/generate/generator/generator.go

Fixes #
```release-note
```
```docs
```

feat: expose the CopyDependentModules method

---

pkg/apis/internal.kusion.io/v1/marshal_test.go
pkg/apis/internal.kusion.io/v1/types.go
pkg/apis/internal.kusion.io/v1/unmarshal_test.go
pkg/cmd/stack/util/util.go
test/e2e/kusionctl_test.go

Fixes #
```release-note
```
```docs
```

feat: adapt to the new service/job workload module

---

pkg/apis/api.kusion.io/v1/types.go
pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go

/kind feature
Fixes #
```release-note
```
```docs
```

feat: add pod labels/annotations in the workload patcher

---

pkg/cmd/workspace/util/testdata/valid_ws.yaml
pkg/engine/api/generate/generator/generator.go
pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go
pkg/modules/util.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go

Fixes #
```release-note
```
```docs
```

feat: validate module path and version in the workspace

---

pkg/engine/api/builders/appconfig_builder.go
pkg/engine/api/generate/run/testdata/base/base.k
pkg/engine/api/generate/run/testdata/prod/kcl.mod
pkg/engine/api/generate/run/testdata/prod/main.k
pkg/engine/api/generate/run/testdata/project.yaml
pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go

/kind bug
#1117 
Fixes #1117 
```release-note
```
```docs
```

fix: customize namespace issue to get correct k8s namespace name

---

pkg/engine/release/storages/local.go
pkg/engine/release/storages/local_test.go
pkg/engine/release/storages/oss.go
pkg/engine/release/storages/s3.go
pkg/engine/release/storages/testdata/releases/test_project/test_ws/.metadata.yml
pkg/engine/release/storages/util.go
pkg/engine/release/storages/util_test.go

Fixes #
```release-note
```
```docs
```

feat: no support of phase in the release metadata

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go

/kind bug
Fixes #
```release-note
```
```docs
```

fix: normalize the k8s workload to fix a deep-copy int error

---

pkg/engine/release/util.go
pkg/modules/generators/app_configurations_generator.go

Fixes #
```release-note
```
```docs
```

chore: optimize some err messages

---

pkg/apis/api.kusion.io/v1/types.go
pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/workload/secret/secret_generator.go
pkg/modules/generators/workload/secret/secret_generator_test.go
pkg/modules/generators/workload/workload_generator.go
pkg/secrets/interfaces.go
pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
pkg/secrets/providers/alicloud/secretsmanager/secretsmanager_test.go
pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
pkg/secrets/providers/aws/secretsmanager/secretsmanager_test.go
pkg/secrets/providers/azure/keyvault/keyvault.go
pkg/secrets/providers/azure/keyvault/keyvault_test.go
pkg/secrets/providers/fake/fake.go
pkg/secrets/providers/fake/fake_test.go
pkg/secrets/providers/hashivault/vault.go
pkg/secrets/providers/hashivault/vault_test.go
pkg/secrets/providers_test.go
pkg/workspace/validation.go
pkg/workspace/validation_test.go

fix: secret store doesn't work
- import the secrets register pkg in the app config generator to register supported secret providers
- rename SecretStoreSpec to SecretStore to prevent misunderstanding of the concept Spec
/kind bug
Fixes #
```release-note
```
```docs
```

fix: import the secrets register pkg in appconfig generator to regist supported secret providers

---

pkg/modules/generators/workload/service_generator_test.go
pkg/modules/generators/workload/workload_generator.go
pkg/modules/generators/workload/workload_generator_test.go

/kind bug
Fixes #1144
```release-note
```
```docs
```

fix: probe type judgment in conversion from kusion probe to k8s probe

---

pkg/cmd/apply/apply.go

/kind bug
This PR sets the release phase as failed when exit the prompt of `kusion apply` due to `SIGINT` or `SIGTERM`. 
Fixes #
```release-note
```
```docs
```

fix: set the release phase as failed when exit apply prompt

---

pkg/domain/constant/source.go
pkg/domain/constant/stack.go

Improved the documentation description
Fixes #
NONE
```release-note
```
```docs
```

fix: improved the documentation description

---

pkg/cmd/stack/util/util.go
pkg/scaffold/quickstart/default/kcl.mod
pkg/scaffold/quickstart/default/main.k

/kind feature
This PR updates the scaffolding templates for `kusion init` and `kusion stack create`. 
Fixes #
```release-note
```
```docs
```

feat: update the init and stack create scaffolding templates

---

pkg/cmd/mod/add.go
pkg/cmd/mod/add_test.go
pkg/engine/api/generate/generator/generator.go

Fixes #
```release-note
```
```docs
```

feat: automatically dowanload kusion modules in the `mod add`

---

pkg/modules/generators/app_configurations_generator.go

Fixes #
```release-note
```
```docs
```

fix: the former module patchers are overridden by the latter one

---

.goreleaser.yml

/kind bug
This PR fixes the goreleaser deprecation notices. 
Fixes #
```release-note
```
```docs
```

fix: goreleaser deprecation notices

---

pkg/apis/api.kusion.io/v1/types.go
pkg/engine/operation/apply.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/models/operation_context.go
pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/workload/secret/secret_generator.go
pkg/modules/generators/workload/secret/secret_generator_test.go
pkg/secrets/interfaces.go
pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
pkg/secrets/providers/alicloud/secretsmanager/secretsmanager_test.go
pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
pkg/secrets/providers/aws/secretsmanager/secretsmanager_test.go
pkg/secrets/providers/azure/keyvault/keyvault.go
pkg/secrets/providers/azure/keyvault/keyvault_test.go
pkg/secrets/providers/fake/fake.go
pkg/secrets/providers/fake/fake_test.go
pkg/secrets/providers/hashivault/vault.go
pkg/secrets/providers/hashivault/vault_test.go
pkg/secrets/providers_test.go

/kind feature
Fixes #1171 
```release-note
```
```docs
```

feat: move secret references replacement form generating to applying

---

pkg/engine/operation/graph/resource_node.go

/kind bug
This PR fixes a bug of replacing secret ref prefix in `kusion apply` command, which skips the secret data without ref prefix. 
Fixes #
```release-note
```
```docs
```

fix: skip replacing secret data without ref prefix

---

pkg/apis/api.kusion.io/v1/types.go
pkg/secrets/providers.go
pkg/secrets/providers_test.go

/kind feature
Now if I want to add new secret provider in specific scene(some secret provider is only use in some company thus it can not be open source), I need to add new provider spec in apis/api.kusion.io/v1. I think apis/api.kusion.io/v1 should be consistent among different use case
Fixes #1177
```release-note
```
```docs
```

feat: add support for on-premises secret provider define in api.kusion.io

---

pkg/apis/api.kusion.io/v1/types.go
pkg/cmd/apply/apply.go
pkg/cmd/preview/preview.go

/kind feature
This PR supports the `--spec-file` flag in `kusion preview` and `kusion apply`. 
Fixes #
```release-note
```
```docs
```

feat: support spec file as input of preview and apply

---

pkg/apis/api.kusion.io/v1/types.go
pkg/backend/storages/s3.go
pkg/config/validation.go

/kind feature
Currently, the endpoint of S3 is only in Virtual-hosted–style: https://bucket_name.s3.example.com/. The error will occur if in the case of S3 Storage Server only supports Certificate for Path-Style like https://s3.example.com/bucket_name/
Fixes #1178
```release-note
```
```docs
```

feat: support path-style of bucket for s3 storage backend

---

.github/workflows/check-md-links.yaml
CONTRIBUTING.md
README.md
docs/cmd/en_US/kusion.md
docs/design/collaboration/collaboration_paradigm.md
docs/design/core_workflow/core_workflow.md
docs/design/secrets_management/secret_management.md
docs/design/workspace_management/workspace_management.md

/kind ci
Fixes #1082 
```release-note
```
```docs
```

ci: check md links periodically

---

pkg/engine/operation/graph/resource_node.go
pkg/engine/runtime/terraform/terraform_runtime.go
pkg/engine/runtime/terraform/tfops/workspace.go

/kind feature
This PR implements the `import` interface for terraform runtime, and supports importing the existing TF resources with Kusion. 
Fixes #286 
```release-note
```
```docs
```

feat: support terraform resource import

---

pkg/cmd/cmd.go
pkg/cmd/release/release.go
pkg/cmd/release/release_test.go
pkg/cmd/release/unlock.go
pkg/cmd/release/unlock_test.go
pkg/cmd/util/helpers.go
pkg/engine/release/util.go

/kind feature
This PR supports the `kusion release unlock` command to unlock the `phase` in `release` file of the current stack, solving the concurrent read-write problem. 
Fixes #1168 
```release-note
```
```docs
```

feat: support release unlock command

---

pkg/util/diff/diff.go
pkg/util/diff/diff_test.go

/kind feature
This PR masks the `data` and `stringData` in `kusion preview` result. 
Fixes #1174 
```release-note
```
```docs
```

feat: mask secret data in preview result

---

.github/workflows/e2e-test.yml
Makefile
docs/design/kusion_module/kusion_modules.md
hack/run-e2e.sh
test/e2e/e2e_suite_test.go
test/e2e/kusionctl_test.go

/kind test
This PR adds windows e2e test for Kusion. 
Fixes #830 #1187 
```release-note
```
```docs
```

test: add windows e2e test

---

docs/design/kusion_module/kusion_modules.md
pkg/engine/runtime/terraform/terraform_runtime.go
pkg/engine/runtime/terraform/terraform_runtime_test.go
pkg/engine/runtime/terraform/tfops/workspace.go
pkg/engine/runtime/terraform/tfops/workspace_test.go

Fixes #
```release-note
```
```docs
```

feat: enable concurrent manipulation of TF resources since they are stored in different directories

---

pkg/engine/runtime/terraform/tfops/workspace.go

/kind bug
Fixes #1196 
```release-note
```
```docs
```

fix: a TF breaking change to enable reusing cached providers

---

pkg/modules/generators/workload/workload_generator.go

/kind bug
Fix volumes deployment
Fixes #1213 
```release-note
```
```docs
```

fix: the latter volume dirs overwrite the prior one

---

pkg/apis/api.kusion.io/v1/types.go
pkg/cmd/apply/apply.go
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destory.go
pkg/engine/operation/graph/resource_node.go
pkg/engine/operation/graph/resource_node_test.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/watch.go
pkg/engine/operation/watch_test.go
pkg/engine/release/util.go
pkg/engine/runtime/init/init.go
pkg/engine/runtime/kubernetes/kubeops/config.go
pkg/engine/runtime/kubernetes/kubernetes_runtime.go
pkg/engine/runtime/terraform/terraform_runtime.go
pkg/engine/runtime/terraform/tfops/workspace.go
pkg/modules/generators/app_configurations_generator.go

/kind feature
This PR adds supports for runtime configurations in workspace. 
Fixes #1192 
```release-note
```
```docs
```

feat: support runtime configurations in workspace

---

pkg/cmd/destroy/destroy.go
pkg/cmd/destroy/destroy_test.go
pkg/engine/operation/models/change.go

/kind bug
This PR fixes the locked `release` file caused by the command interruption (`SIGINT` or `SIGTERM`) when executing `kusion destroy`. 
Fixes #1167 
```release-note
```
```docs
```

fix: locked release file caused by interruption

---

pkg/util/diff/diff.go

/kind bug
This PR fixes a bug of deep copying resource attributes when getting the diff report. 
Fixes #
```release-note
```
```docs
```

fix: deep copy resource attributes

---

pkg/cmd/apply/apply.go

/kind feature
This PR optimizes the terminal UI for `kusion apply`. 
Fixes #1170 
```release-note
```
```docs
```

feat: optimize terminal ui for kusion apply

---

pkg/modules/generators/app_configurations_generator.go

Fixes #1243
```release-note
```
```docs
```

fix: return more detailed error msg with JsonPatch

---

pkg/cmd/mod/push.go

/kind cleanup
remove duplicate equal sign in mod push cmd comments
Fixes #
```release-note
```
```docs
```

fix: duplicate equal sign in mod push cmd comments

---

pkg/cmd/destroy/destroy.go

/kind bug
This PR uses `copier.Copy` to deeply copy the `Release` to be updated in `kusion destroy` command.  
Fixes #
```release-note
```
```docs
```

fix: deep copy release to update when destroy

---

pkg/engine/runtime/terraform/terraform_runtime.go
pkg/modules/generators/app_configurations_generator.go

- Currently, when we add a resource to the workspace with importedResources, every time we kusion apply a project in that workspace, we will be required to use that or every imported resources. This will cause some projects that do not use imported resources to be unable to apply.
- One more problem is when applying, the terraform resource that was declared in the workspace, in the phase generate from .k to spec the attributes of it will still receive data by kusion catalog so when we import, the action of it becomes Update not UnChanged. So the resource will update unnecessary fields.
/kind feature
Fixes #1259 
```release-note
```
```docs
```

feat: remove requirement to use imported resource when apply

---

pkg/cmd/release/list.go
pkg/cmd/release/list_test.go
pkg/cmd/release/release.go

Feat: Add a new command kusion release list to list all releases in one workspace
/kind feature
Usage: Fixes #1093  Part-1.
Feat: Add a new command kusion release list to list all releases in one workspace.
Everything works well /lgtm
before only unlock command used to show, now list command can also be seen below:
All edge cases also covered if, user has no workspace, it throws error as seen in Picture.
```release-note
In this PR we fix the sub command issue: #1093 Part-1 
Add a new command kusion release list to list all releases in one workspace.
when use kusion release,
It now shows list with unlock.
```
```docs
I will make add the docs separately in another PR and explain how the system.
```
@SparkYuan Please review the PR.
/lgtm

feat: add a new command kusion release list

---

pkg/cmd/release/release.go
pkg/cmd/release/show.go
pkg/cmd/release/show_test.go

/kind feature
This command displays detailed information about a release of the current project in the current or a specified workspace.
Fixes #1262 
```release-note
```
```docs
```

feat: add kusion release show command

---

pkg/apis/api.kusion.io/v1/types.go
pkg/cmd/apply/apply.go
pkg/cmd/apply/apply_test.go
pkg/engine/printers/generate.go
pkg/modules/generators/app_configurations_generator.go
pkg/util/kcl/kcl.go
pkg/util/kcl/kcl_test.go

Fixes #1254
```release-note
```
```docs
```

feat: add KCL based customized health check

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/generators/app_configurations_generator_test.go

/kind feature
This PR adds the support for removal env patcher. 
Fixes #1271
```release-note
```
```docs
```

feat: support removal env patcher

---

pkg/cmd/apply/apply.go
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destroy.go
pkg/engine/operation/preview.go
pkg/engine/operation/preview_test.go
pkg/engine/operation/watch.go
pkg/engine/operation/watch_test.go
pkg/engine/runtime/init/init.go

/kind bug
This PR fixes a bug of initializing Kusion's runtimes with `release.State` as input. 
Fixes #1287 
```release-note
```
```docs
```

fix: init runtime with state

---

pkg/apis/api.kusion.io/v1/types.go
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/operation/destroy.go
pkg/engine/operation/models/operation_context.go
pkg/engine/operation/models/operation_context_test.go
pkg/engine/operation/preview.go

/kind feature
This PR adds support for maximum number of concurrent resource operation executions. Users can set the value with the `KUSION_EXEC_MAX_CONCURRENT` environment variable, which defaults to `10`. 
Fixes #1198 
```release-note
```
```docs
```

feat: support max number of concurrent resource operation executions

---

pkg/apis/api.kusion.io/v1/types.go
pkg/backend/backend.go
pkg/backend/storages/local.go
pkg/backend/storages/local_test.go
pkg/backend/storages/oss.go
pkg/backend/storages/oss_test.go
pkg/backend/storages/s3.go
pkg/backend/storages/s3_test.go
pkg/cmd/apply/apply.go
pkg/cmd/apply/apply_test.go
pkg/cmd/destroy/destroy.go
pkg/cmd/release/list_test.go
pkg/cmd/release/show_test.go
pkg/cmd/release/unlock_test.go
pkg/cmd/resource/graph.go
pkg/cmd/resource/resource.go
pkg/engine/operation/apply.go
pkg/engine/operation/apply_test.go
pkg/engine/resource/graph/storage.go
pkg/engine/resource/graph/storages/local.go
pkg/engine/resource/graph/storages/oss.go
pkg/engine/resource/graph/storages/s3.go
pkg/engine/resource/graph/storages/util.go
pkg/engine/resource/graph/util.go
pkg/engine/resource/graph/validation.go
pkg/modules/generators/app_configurations_generator.go

Fixes #1277
```release-note
```
```docs
```

feat: add resource graph command

---

pkg/cmd/resource/resource.go
pkg/cmd/resource/show.go
pkg/cmd/resource/show_test.go

/kind feature
Show details of a resource of the current or specified stack.
Fixes #1261
```release-note
```
```docs
```

feat: add resource show command

---

api/openapispec/docs.go
api/openapispec/swagger.json
api/openapispec/swagger.yaml
pkg/domain/entity/module.go
pkg/domain/repository/repository.go
pkg/domain/request/module_request.go
pkg/infra/persistence/module.go
pkg/infra/persistence/module_model.go
pkg/infra/persistence/types.go
pkg/infra/persistence/util.go
pkg/server/handler/module/handler.go
pkg/server/handler/module/types.go
pkg/server/manager/module/module_manager.go
pkg/server/manager/module/types.go
pkg/server/route/route.go

/kind feature
This PR adds the implementation of module-related apis for kusion server. 
Fixes #
```release-note
```
```docs
```

feat: add kusion module apis for server

---

pkg/infra/persistence/resource.go
pkg/infra/persistence/run.go
pkg/infra/persistence/stack.go
pkg/infra/persistence/util.go
pkg/infra/persistence/util_test.go

/kind bug
This PR fixes the issues of the table name case sensitivity in `JOIN` and pattern statement. 
Fixes #
```release-note
```
```docs
```

fix: table name case sensitivity in join and pattern statement

---

pkg/domain/constant/run.go

Fixes #
```release-note
```
```docs
```

fix: able to parse run type and status in in any cases

---

pkg/domain/constant/global.go
pkg/domain/constant/organization.go
pkg/domain/entity/run.go
pkg/domain/entity/types.go
pkg/domain/repository/repository.go
pkg/domain/response/resource.go
pkg/domain/response/run.go
pkg/infra/persistence/run.go
pkg/infra/persistence/run_model.go
pkg/server/handler/stack/execute_async.go
pkg/server/handler/stack/run.go
pkg/server/handler/stack/utils.go
pkg/server/manager/stack/execute.go
pkg/server/manager/stack/run.go
pkg/server/manager/stack/util.go

Fixes #
```release-note
```
```docs
```

chore: optimize runs api

---

pkg/modules/generators/app_configurations_generator.go
pkg/modules/plugin.go

feat: add trace for module and split module logs
https://github.com/KusionStack/kusion/issues/1304
```release-note
```
```docs
```

feat: add trace for module and split module logs

---

pkg/server/handler/stack/utils.go
pkg/server/manager/stack/execute.go
pkg/server/manager/stack/types.go
pkg/server/manager/stack/util.go

Fixes #
```release-note
```
```docs
```

feat: enable force unlock and optimize failure handling in execute api

---

pkg/engine/api/apply.go
pkg/engine/api/preview.go
pkg/engine/release/util.go
pkg/engine/runtime/kubernetes/kubernetes_runtime.go
pkg/generators/appconfiguration/app_configurations_generator.go
pkg/server/handler/stack/utils.go
pkg/server/manager/stack/execute.go
pkg/server/manager/stack/types.go
pkg/server/manager/stack/util.go
pkg/server/util/logging/logger.go

Support watching Kubernetes resources during apply:
- Apply will finish when reconcile is done
- You can specify custom health policy for each individual resources in workspace configuration
- You can specify watch timeout (in seconds) in case the synchronous apply takes forever to return
- When the specified timeout is reached, this watch operation is considered completed and apply will return
Example customized health policy:
`workspace.yaml`:
```
context:
KUBECONFIG_PATH: /Users/forest/.minikube.kubeconfig
modules:
network:
path: oci://ghcr.io/kusionstack/network
version: 0.2.0
configs:
default:
healthPolicy:
apiVersion: v1
kind: Service
health.kcl: |
import regex
watchAnnotationKey = "network.beta.kubernetes.io/watch"
assert any k in res.metadata.annotations {
regex.match(k, …
```

feat: support watch in runs

---

pkg/apis/api.kusion.io/v1/resource.go
pkg/engine/operation/graph/resource_node.go

bug
Resource dependency status maintenance and improvement needs
Fixes #1358
```release-note
Solve the problem that the resources have not changed but the dependencies have changed, but the resource dependencies in status maintenance have not changed.
```
```docs
```

fix: the problem of dependency change status not being updated

---

api/openapispec/docs.go
api/openapispec/swagger.json
api/openapispec/swagger.yaml
go.mod
pkg/server/handler/backend/handler.go
pkg/server/handler/module/handler.go
pkg/server/handler/organization/handler.go
pkg/server/handler/project/handler.go
pkg/server/handler/resource/handler.go
pkg/server/handler/source/handler.go
pkg/server/handler/stack/execute.go
pkg/server/handler/stack/execute_async.go
pkg/server/handler/stack/handler.go
pkg/server/handler/stack/run.go
pkg/server/handler/workspace/configs.go
pkg/server/handler/workspace/handler.go

/kind bug
This PR fixes the kusion server handler swagger apis. 
Fixes #
```release-note
```
```docs
```

fix: kusion server handler swagger apis

---

api/openapispec/docs.go
api/openapispec/swagger.json
api/openapispec/swagger.yaml
pkg/apis/api.kusion.io/v1/types.go
pkg/domain/constant/workspace.go
pkg/domain/request/workspace_request.go
pkg/server/handler/module/handler.go
pkg/server/handler/stack/handler.go
pkg/server/handler/workspace/configs.go
pkg/server/handler/workspace/handler.go
pkg/server/manager/backend/backend_manager.go
pkg/server/manager/backend/types.go
pkg/server/manager/backend/util.go

avoid displaying sensitive data to user
Fixes #
```release-note
```
```docs
```

chore: mask backend sensitive data

---

pkg/generators/appconfiguration/app_configurations_generator.go

/kind feature
This PR adds support for removal ability of label and annotation patcher. 
Fixes #
```release-note
```
```docs
```

feat: support patcher removal for label and annotation

---

api/openapispec/docs.go
api/openapispec/swagger.json
api/openapispec/swagger.yaml
pkg/domain/constant/project.go
pkg/domain/entity/project.go
pkg/infra/persistence/util.go
pkg/server/handler/project/handler.go
pkg/server/manager/project/project_manager.go

support fuzzy match project name
Fixes #
```release-note
```
```docs
```

chore: support fuzzy match project name

---

pkg/infra/persistence/project_model.go
pkg/infra/persistence/resource_model.go
pkg/infra/persistence/run_model.go
pkg/infra/persistence/workspace_model.go

Fixes #
```release-note
```
```docs
```

fix: use default foreign key

---

api/openapispec/docs.go
api/openapispec/swagger.json
api/openapispec/swagger.yaml
pkg/domain/constant/global.go
pkg/domain/entity/types.go
pkg/domain/repository/repository.go
pkg/infra/persistence/project.go
pkg/infra/persistence/project_test.go
pkg/infra/persistence/run.go
pkg/server/handler/module/handler.go
pkg/server/handler/project/handler.go
pkg/server/handler/stack/handler.go
pkg/server/handler/stack/run.go
pkg/server/handler/workspace/configs.go
pkg/server/manager/project/project_manager.go
pkg/server/manager/project/project_manager_test.go
pkg/server/manager/project/util.go
pkg/server/manager/stack/run.go
pkg/server/manager/stack/stack_manager_test.go
pkg/server/manager/stack/util.go

Fixes #
```release-note
```
```docs
```

feat: add sort options in runs and projects list api

---

Makefile
README.md

Fixes #
```release-note
```
```docs
```

docs: update README.md

---

pkg/engine/api/apply.go
pkg/engine/operation/apply.go

/kind bug
Fixes #
fix: apply failure will cause release state to be completely empty
```release-note
fix: apply failure will cause release state to be completely empty
```
```docs
fix: apply failure will cause release state to be completely empty
```

fix: apply failure will cause release state to be completely empty

---

ui/package.json

Fixes #
```release-note
```
```docs
```

chore: bump kusion-api-client-sdk from 1.1.4 to 1.1.5

---

pkg/cmd/preview/preview.go
pkg/server/manager/stack/execute.go

/kind feature 
It is actually valid to pass an empty spec for a preview, and Kusion should handle the preview result correctly.
This change should not affect how apply and destroy handle an empty spec.
Fixes #1419 
```release-note
```
```docs
```

feat: handle empty stack in preview

---

pkg/secrets/interfaces.go
pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
pkg/secrets/providers/azure/keyvault/keyvault.go
pkg/secrets/providers/fake/fake.go
pkg/secrets/providers/hashivault/vault.go
pkg/secrets/providers/viettelcloud/secretsmanager/secretsmanager.go
pkg/secrets/providers_test.go

/kind feature
add interface SetSecret and empty implement in secrets provider.
Fixes https://github.com/KusionStack/kusion/issues/1411
```release-note
```
```docs
```

feat: add interface SetSecret in secrets provider

---

pkg/cmd/server/options.go
pkg/server/route/route.go

/kind bug
Fixes #1421 
```release-note
NONE
```
```docs
```

fix: capture http server errors
