- pkg/compile/compile.go
- pkg/engine/operation/change.go
- pkg/engine/operation/change_test.go
- pkg/util/pretty/prefix_printer.go
- pkg/util/pretty/prefix_text_printer.go
- optimize apply ui
- fix pretty printer style feild
#19
> chore: optimize apply ui and fix pretty printer style feild

- Dockerfile
Purpose:
* change base image from centos:centos7 to ubuntu:18.04
* adjust the dependency in Dockerfile
> chore: adjust base image, dependency in Dockerfile

- README-zh.md
- README.md
Purpose:
* refine "Build from Source" for README
> docs: refine "Build from Source" for README

- pkg/compile/type.go
- pkg/compile/type_test.go
- pkg/kusionctl/cmd/compile/options.go
related issue: https://github.com/KusionStack/kusion/issues/41
> fix: build compiled yaml string base on kcl schema definition

- pkg/util/kdump/kdump.go
- pkg/util/kdump/types.go
Purpose:
* refine kdump package
> refactor: refine kdump package

- .github/CODEOWNERS
`.github/CODEOWNERS`
```release-note
None
```
> chore: replace account id with dev team id

- Makefile
- go.mod
- go.sum
> fix: build script, replace kcl-go

- third_party/README.md
close: https://github.com/KusionStack/kusion/issues/61
each section mainly contains:
- original repo address
- package description
- changes authored by KusionStack
> chore: update readme of third party

- go.sum
- pkg/kusionctl/cmd/compile/compile.go
- pkg/kusionctl/cmd/compile/options.go
- pkg/log/log.go
- pkg/log/log_test.go
- pkg/log/types.go
- pkg/log/zap.go
fix: https://github.com/KusionStack/kusion/issues/75
> feat: util/log support log to stderr and add log-to-stderr flag for kusion compile

- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/models/change.go
- pkg/engine/operation/models/change_test.go
- pkg/engine/operation/preview_test.go
- pkg/engine/runtime/kubernetes_runtime.go
- pkg/kusionctl/cmd/apply/options_test.go
- pkg/kusionctl/cmd/destroy/options_test.go
- pkg/util/diff/util.go
- pkg/util/diff/util_test.go
- pkg/util/yaml/yaml.go
related issue: https://github.com/KusionStack/kusion/issues/51
> feat: three way diff, compare live config with dry-run result

- pkg/engine/operation/graph/resource_node.go
- pkg/engine/states/local/filesystem_state.go
- pkg/engine/states/remote/db_state.go
- pkg/kusionctl/cmd/apply/options.go
pkg/kusionctl/cmd/apply
pkg/engine/states/local/
1. Parse field `Cluster` From Resource.Extensions in CLI
2. Rollback yaml.v3 to v2 for a known bug in v3
```release-note
None
```
> Parse field `Cluster` From Resource.Extensions in CLI

- pkg/engine/runtime/kubernetes_runtime.go
close: https://github.com/KusionStack/kusion/issues/98
> bugfix: use client side dry-run to be compatible with server side dry-run not support

- README.md
> docs: update installation ways

- go.mod
- go.sum
chore: bump kclvm version to v0.4.3-alpha.2
KCLVM Release Note: https://github.com/KusionStack/KCLVM/releases/tag/v0.4.2-alpha.5
> chore: bump kclvm version to v0.4.3-alpha.3

- .github/workflows/release.yaml
- Dockerfile_kusionctl
fix #92 
.github/workflows/release.yaml
Dockerfile_kusionctl
This PR support producing a kusionctl image in release pipeline.
```release-note
None
```
> support release kusionctl image

- docs/backend.md
- pkg/engine/backend/backend.go
- pkg/engine/backend/backend_test.go
- pkg/engine/backend/init/init.go
- pkg/engine/states/backend.go
- pkg/engine/states/local/backend.go
- pkg/engine/states/local/backend_test.go
- pkg/engine/states/local/filesystem_state.go
- pkg/engine/states/local/filesystem_state_test.go
- pkg/engine/states/remote/db_state.go
- pkg/kusionctl/cmd/apply/apply.go
- pkg/kusionctl/cmd/apply/options.go
- pkg/kusionctl/cmd/destroy/destroy.go
- pkg/kusionctl/cmd/destroy/options.go
- pkg/kusionctl/cmd/destroy/options_test.go
- pkg/projectstack/types.go
re #114 
pkg/engine/backend
pkg/engine/states/local
support diff backend store state, more detail docs/backend.md
```release-note
None
```
> feat: support kusion state remote storage

- go.mod
- go.sum
chore: bump kclvm version to v0.4.3-alpha.4
```release-note
None
```
KCLVM Release Note: https://github.com/KusionStack/KCLVM/releases/tag/v0.4.3-alpha.1
> chore: bump kclvm version to v0.4.3-alpha.4

- pkg/engine/operation/models/operation_context.go
pkg/engine/operation/models/operation_context.go
Fix error msg
```release-note
None
```
> fix error msg

- pkg/engine/doc.go
pkg/engine/doc.go
update engine doc
```release-note
None
```
> update engine doc

- pkg/engine/printers/k8s/convertors.go
- pkg/engine/printers/k8s/printers.go
related: https://github.com/KusionStack/kusion/issues/23#issuecomment-1272855221
> feat: kusion watch supports resources of corev1 kinds

- pkg/compile/compile.go
- pkg/compile/util.go
- pkg/engine/kcl.go
- pkg/engine/util.go
- pkg/resources/crd/crd.go
pkg/compile
Convert CRDs to Resource in operation compile to adapt the latest compile result
```release-note
None
```
> Fix: convert CRDs to Resource in operation compile to adapt the latest compile result

- go.mod
- go.sum
> chore: bump kclvm-go version to v0.4.4-alpha.1

- pkg/engine/printers/k8s/convertors.go
- pkg/engine/printers/k8s/printers.go
related: https://github.com/KusionStack/kusion/issues/23#issuecomment-1272887975
> feat: kusion watch supports apps/v1 resources

- pkg/engine/printers/k8s/convertors.go
- pkg/engine/printers/k8s/printers.go
related: https://github.com/KusionStack/kusion/issues/167
related: https://github.com/KusionStack/kusion/issues/23#issuecomment-1272888285
> feat: kusion watch supports batch/v1 resources

- pkg/engine/operation/graph/resource_node.go
close: https://github.com/KusionStack/kusion/issues/169
> bugfix: correct resource change action

- pkg/kusionctl/cmd/cmd.go
thanks to @Peefy for this delightful tip
> chore: add note to skip version upgrade check

- pkg/engine/runtime/terraform/terraform_runtime.go
- pkg/engine/runtime/terraform/tfops/workspace.go
* change the terraform resource id to be separated by ":"
* fix terraform init error output
* pkg/engine/runtime/terraform
```release-note
None
```
> update tf resource id and fix tf error output

- pkg/engine/runtime/kubernetes_runtime.go
1. For k8s Service, automatically choose Endpoints or EndpointSlice to watch. For k8s version < v1.21, no `discovery.k8s.io/v1/EndpointSlice` API
2. use `owner/dependent` relation for k8s workloads, leave `selector` for extension
> kusion watch: refine k8s resource relation

- Makefile
- doc.go
- hack/run-e2e.sh
- kusion.go
> refactor: rename kusionctl to kusion

- pkg/engine/runtime/terraform/terraform_runtime.go
pkg/engine/runtime/terraform/terraform_runtime.go
```release-note
None
```
> fix tf state id

- pkg/kusionctl/cmd/compile/options.go
close: https://github.com/KusionStack/kusion/issues/205
> bugfix: preset o.Settings and o.Output separately

- Dockerfile
- Dockerfile_kusionctl
fix: #213. chore: bump dockerfile base image to ubuntu:22.04
```release-note
None
```
> chore: bump dockerfile base image to ubuntu:22.04

- pkg/kusionctl/cmd/compile/compile_test.go
- pkg/kusionctl/cmd/compile/options.go
pkg/kusionctl/cmd/compile/options.go
fix kusion compile terminal output，when run `kusion compile -o stdout`, kusion compile result output in terminal.
```release-note
None
```
> fix kusion compile terminal output

- pkg/engine/operation/graph/resource_node.go
auto import resources exist in spec and live cluster but no recorded in kusion_state.json
> auto import resources exist in spec and live cluster but no recorded in kusion_state.json

- pkg/engine/runtime/terraform/tfops/workspace.go
pkg/engine/runtime/terraform/tfops/workspace.go
Support log output to `kusion-debug.log`  when kusion tf runtime provider is executed
```release-note
None
```
> support provider log output

- README-zh.md
- README.md
related: https://github.com/KusionStack/kusion/issues/233
> bugfix: update go install command

- .goreleaser.yml
Release scoop package for windows users by goreleaser.
> feat: support scoop install for windows

- pkg/engine/operation/graph/resource_node.go
/kind bug
bug fix
```release-note
```
```docs
```
> fix log npe

- README-zh.md
- README.md
> polish README.md

- README-zh.md
- README.md
polish readm
Fixes #
NONE#### Does this PR introduce a user-facing change?
```release-note
NONE
```
```docs
NONE
```
> polish readme

- .goreleaser.yml
/kind feature
Add brew dependencies for kusion, so brew install kusion will trigger install kclvm first
Fixes #
```release-note
NONE
```
```docs
```
> add brew dependencies

- pkg/engine/runtime/terraform/tfops/tferrors.go
/kind bug
fix tf parsing errors
```release-note
none
```
```docs
none
```
> fix tf parsing errors

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/enhancement.yaml
- .github/ISSUE_TEMPLATE/failing-test.yaml
> update the issue template

- pkg/engine/printers/printer/oam_printer.go
close: https://github.com/KusionStack/kusion/issues/281
> refactor: default status to none and move phase to first

- pkg/engine/runtime/terraform/terraform_runtime_test.go
- pkg/engine/runtime/terraform/tfops/workspace.go
- pkg/engine/runtime/terraform/tfops/workspace_test.go
/kind bug
fix delete-and-create when updating TF resources
Fixes #268 
none
```release-note
none
```
```docs
none
```
> fix delete-and-create when updating TF resources

- third_party/terraform/dag/walk.go
/kind cleanup
do not show dag/walk log in the terminal
> change dag/walk log to normal kusion log

- pkg/engine/runtime/terraform/terraform_runtime.go
- pkg/engine/runtime/terraform/tfops/workspace.go
- pkg/util/io/dir.go
/kind feature
Cache TF Providers to speed up operations
Fixes #290 
none
```release-note
none
```
```docs
none
```
> Cache TF Providers to speed up operations

- pkg/engine/operation/parser/delete_resource_parser.go
- pkg/engine/operation/parser/parser.go
- pkg/engine/operation/parser/spec_parser.go
/kind bug
add resource dependencies in the destroy operation
Fixes #298 
none
```release-note
none
```
```docs
none
```
> add resource dependencies in the destroy operation

- pkg/cmd/destroy/options.go
- pkg/cmd/destroy/options_test.go
- pkg/engine/operation/destory_test.go
> fix npe in destroy

- README-zh.md
- README.md
Updated inaccessible links in README
Replace some links in the Readme-zh with Chinese documentation links
Fixes #306
> docs: update links in readme

- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/graph/resource_node_test.go
/kind cleanup
refactor ResourceNode.execute to make it more readable
none
```release-note
none
```
```docs
none
```
> refactor ResourceNode.execute to make it more readable

- pkg/engine/operation/apply.go
- pkg/engine/operation/destory.go
- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/parser/parser.go
- pkg/engine/operation/preview.go
- pkg/engine/runtime/terraform/terraform_runtime.go
/kind feature
replace implicit dependency in operation preview
Fixes #295 
none
```release-note
replace implicit dependencies in resources during the operation preview to prevent unnecessary `update` actions 
```
```docs
none
```
> Replace implicit dependencies in resources during the operation preview

- pkg/engine/operation/graph/resource_node.go
/kind bug
Fix error when applying Kubernetes resource for the second time
none
```release-note
none
```
```docs
```
> revert a mistaken modification

- README-zh.md
- README.md
add windows installation guide and Shift Risk Left key features in readme
Fixes #
```release-note
```
```docs
```
> add windows installation guide and Shift Risk Left key features

- pkg/cmd/apply/options.go
- pkg/cmd/preview/options.go
- pkg/cmd/util/helpers.go
- pkg/cmd/util/helpers_test.go
/kind cleanup
cleanup
Fixes #
none
```release-note
none
```
```docs
```
> parse `cluster` from cmd args

- .github/workflows/e2e-test.yml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- Dockerfile
- go.mod
- scripts/install-kcl-openapi/go.mod
/kind feature
Upgrade to go 1.19 to be compatible with the new k8s version
> upgrade to go 1.19

- go.mod
- go.sum
- pkg/util/io/io.go
- pkg/util/io/io_test.go
/kind cleanup
delete unused kustomize related codes to cleanup go.mod
> delete unused kustomize related codes to cleanup go.mod

- README-zh.md
- README.md
update the demo video in readme.md
> update readme demo

- go.mod
- go.sum
/kind release
chore: bump kcl version to v0.5.0-alpha.3
+ Ref: https://github.com/KusionStack/kcl/releases/tag/v0.5.0-alpha.3
> chore: bump kcl version to v0.5.0-alpha.3

- README-zh.md
- README.md
add apply gif in the readme
Fixes #
```release-note
```
```docs
```
> add apply gif in the readme

- pkg/cmd/apply/options.go
- pkg/cmd/apply/options_test.go
- pkg/cmd/destroy/options.go
- pkg/cmd/destroy/options_test.go
- pkg/cmd/preview/options_test.go
- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/models/action.go
- pkg/engine/operation/models/change.go
- pkg/engine/operation/models/change_test.go
- pkg/engine/operation/models/operation_context.go
change the typo 'unchange' action type to `unchanged`
Fixes #
```release-note
change the typo 'unchange' action type to `unchanged`
```
```docs
```
> change the typo 'unchange' action type to `unchanged`

- pkg/cmd/preview/options.go
- pkg/cmd/preview/options_test.go
- pkg/cmd/spec/generator.go
/kind bug
```release-note
```
```docs
```
> do not show generating hint in the command preview

- pkg/cmd/compile/options.go
/kind feature
update compile output to a complete spec
Fixes #410 
```release-note
Update compile result form Spec.resources to a complete Spec
```
```docs
```
> update compile output to a complete spec

- pkg/cmd/spec/generator.go
- pkg/generator/app_configuration/app_config_generator.go
- pkg/models/appconfiguration/appconfiguration.go
- pkg/models/appconfiguration/component/component.go
- pkg/models/appconfiguration/component/container/container.go
/kind feature
Add AppConfiguration model definition implemented in golang.
> feat: add app configuration model in golang

- pkg/cmd/compile/options_test.go
- pkg/models/appconfiguration/component/component.go
- pkg/models/appconfiguration/component/job/job.go
/kind feature
Support native Job resource in AppConfiguration model.
> feat: add job type to generator

- pkg/generator/appconfiguration/generators/components_generator.go
- pkg/generator/appconfiguration/generators/deployment_generator.go
- pkg/generator/appconfiguration/generators/namespace_generator.go
- pkg/generator/appconfiguration/generators/util.go
/kind feature
Implement deployment generator in AppConfiguration.
> feat: implement deployment generator

- pkg/generator/appconfiguration/generators/components_generator.go
- pkg/generator/appconfiguration/generators/deployment_generator.go
- pkg/generator/appconfiguration/generators/util.go
/kind refactor
Use ordered map for component and container. Otherwise, each compilation result will be different.
> refactor: use ordered map for component and container

- pkg/generator/appconfiguration/generators/components_generator.go
- pkg/generator/appconfiguration/generators/deployment_generator.go
- pkg/generator/appconfiguration/generators/job_generator.go
- pkg/generator/appconfiguration/generators/job_generator_test.go
- pkg/generator/appconfiguration/generators/util.go
- pkg/models/appconfiguration/component/component.go
- pkg/models/appconfiguration/component/job/job.go
- pkg/models/appconfiguration/component/workload/job.go
- pkg/models/appconfiguration/component/workload/long_running_service.go
/kind feature
add job generator to adapt to the latest app model.
Fixes #374
> feat: add job generator

- docs/prometheus.md
Design doc for kusion's Prometheus support mentioned in #383
> doc: Add design documentation for Prometheus support in kusion

- pkg/models/appconfiguration/workload/workload.go
- pkg/models/appconfiguration/workload/workload_test.go
/kind feature
Customize workload deserialization and serialization for `yaml` by type.
> feat: customize workload deserialization and serialization for yaml by type

- pkg/generator/appconfiguration/generator/namespace_generator.go
/kind bug
This PR fixes a bug which may generate duplicate namespaces with the same ID when users defines multiple applications in one project. 
Fixes #
```release-note
```
```docs
```
> fix: avoid generating duplicate namespaces

- pkg/generator/appconfiguration/generator/app_configurations_generator_test.go
- pkg/generator/appconfiguration/util_test.go
/kind test
Complete generator unit test
> test: complete generator unit test

- pkg/models/appconfiguration/workload/container/container.go
- pkg/models/appconfiguration/workload/container/container_test.go
/kind feature
add probe types and encoding/decoding support
Fixes #
```release-note
```
```docs
```
> feat: add probe types and encoding/decoding support

- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/parser/parser.go
/kind bug
fix type mismatch in replacing implicit dependencies
Fixes #
```release-note
```
```docs
```
> fix: type mismatch in replacing implicit dependencies

- pkg/cmd/spec/generator.go
- pkg/cmd/spec/generator_test.go
- pkg/generator/kcl/kcl_generator.go
/kind feature
only support kcl schema type in the AppConfig generator to avoid unnecessary diffs
Fixes #489 
```release-note
```
```docs
```
> feat: only support kcl schema type in the AppConfig generator

- pkg/engine/operation/apply.go
- pkg/engine/operation/destory.go
- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/preview.go
/kind bug
fix: error messages are ignored when executing resource nodes
> fix: error messages are ignored when executing resource nodes

- pkg/generator/appconfiguration/generator/workload/job_generator.go
/kind bug
This PR fixes a coding mistake which uses reference to loop iterator variable. 
Fixes #
```release-note
```
```docs
```
> fix: fix a coding mistake

- pkg/generator/appconfiguration/generator/app_configurations_generator_test.go
- pkg/generator/appconfiguration/generator/workload/network/ports_generator.go
- pkg/generator/appconfiguration/generator/workload/network/ports_generator_test.go
- pkg/generator/appconfiguration/generator/workload/service_generator.go
- pkg/generator/appconfiguration/generator/workload/service_generator_test.go
- pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
- pkg/models/appconfiguration/workload/network/port.go
- pkg/models/appconfiguration/workload/service.go
/kind feature
add network port generator
> feat: add network port generator

- third_party/terraform/dag/walk.go
/kind bug
fix incorrect dag walk log messages
Fixes #
```release-note
```
```docs
```
> fix: incorrect dag walk log messages

- pkg/generator/appconfiguration/generator/accessories/database/alicloud_rds.go
/kind feature
update the version of alicloud provider
Fixes #
```release-note
```
```docs
```
> chore: update the version of alicloud provider

- pkg/generator/appconfiguration/generator/trait/ops_rule_generator.go
- pkg/generator/appconfiguration/generator/trait/ops_rule_generator_test.go
/kind bug
add maxUnavailable in OpsRule
Fixes #
```release-note
```
```docs
```
> fix: add maxUnavailable in OpsRule

- pkg/engine/operation/graph/resource_node.go
/kind bug
fix invalidate dependency replacement in preview
Fixes #
```release-note
```
```docs
```
> fix: invalidate dependency replacement in preview

- pkg/generator/appconfiguration/generator/workload/workload_generator.go
/kind bug
Fix occasional unit test failures for generator.
> fix: occasional ut failures for generator

- .github/workflows/constraint.yaml
/kind chore
Fixes #
update pr title max length
```release-note
```
```docs
```
> chore: update pr title max length

- go.mod
- go.sum
- pkg/generator/kcl/kcl_generator.go
/kind bug
fix compile error with -w flag in kpm mode
Fixes #537 
```release-note
```
```docs
```
> fix: compile error with -w flag in kpm mode

- pkg/cmd/spec/generator.go
- pkg/generator/appconfiguration/generator/accessories/database/database_generator.go
- pkg/generator/appconfiguration/generator/workload/workload_generator.go
- pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
- pkg/models/appconfiguration/workload/container/container.go
- pkg/models/appconfiguration/workload/container/container_test.go
/kind feature
This PR uses MapSlice in yaml.v2 package for container env so that the order of the environment variables can stay consistent. 
Fixes #503 
```release-note
```
```docs
```
> feat: use map slice for container env

- pkg/generator/appconfiguration/generator/accessories/database/alicloud_rds_test.go
- pkg/generator/appconfiguration/generator/accessories/database/aws_rds_test.go
- pkg/generator/appconfiguration/generator/accessories/database/database_generator.go
- pkg/generator/appconfiguration/generator/accessories/database/database_generator_test.go
/kind feature
This PR adds unit tests for database generator. 
Fixes #541 
```release-note
```
```docs
```
> test: add unit tests for database generator

- docs/contributing.md
/kind feature
add contributing.md
Fixes #514
> feat: add contributing.md

- pkg/generator/appconfiguration/generator/app_configurations_generator_test.go
- pkg/generator/appconfiguration/generator/workload/network/ports_generator.go
- pkg/generator/appconfiguration/generator/workload/network/ports_generator_test.go
- pkg/generator/appconfiguration/generator/workload/service_generator.go
- pkg/generator/appconfiguration/generator/workload/service_generator_test.go
- pkg/generator/appconfiguration/generator/workload/workload_generator_test.go
- pkg/models/appconfiguration/workload/network/port.go
/kind feature
Support aws clb in ports model.
> feat: support aws clb in ports model

- pkg/generator/appconfiguration/generator/workload/secret_generator.go
- pkg/generator/appconfiguration/generator/workload/secret_generator_test.go
- pkg/generator/appconfiguration/generator/workload/workload_generator.go
- pkg/models/appconfiguration/workload/common.go
- pkg/models/appconfiguration/workload/secret.go
Fixes #
```release-note
```
```docs
```
> feat: add plain secret generator

- test/e2e/kusionctl_test.go
Fix wrong e2e test as adjust konfig directory
> fix: wrong e2e test as new konfig dir

- test/e2e/kusionctl_test.go
/kind testing
fix: wrong e2e test again
> fix: wrong e2e test again

- pkg/cmd/preview/options.go
- pkg/cmd/spec/generator.go
- pkg/cmd/spec/generator_test.go
/kind bug
Fix the issue of failing to parse spec file.
> fix: the issue of failing to parse spec file

- pkg/generator/appconfiguration/generator/accessories/database/database_generator.go
- pkg/generator/appconfiguration/generator/accessories/database/local_database.go
- pkg/generator/appconfiguration/generator/accessories/database/local_database_test.go
/kind feature
This PR adds support for local database generator and related unit tests. 
Fixes #556 
An example of deploying WordPress application with local database is shown below. 
```release-note
```
```docs
```
> feat: add local database generator and related unit tests

- docs/design/appconfiguration_generator.md
Refs #529
```release-note
NONE
```
```docs
```
> docs: add refactor proposal for appConfiguration generator

- pkg/engine/operation/apply.go
- pkg/engine/operation/apply_test.go
- pkg/engine/operation/destory.go
- pkg/engine/operation/preview.go
- pkg/engine/operation/preview_test.go
- pkg/engine/operation/watch.go
- pkg/engine/operation/watch_test.go
- pkg/engine/runtime/init/init.go
- pkg/engine/runtime/kubernetes/kubernetes_runtime.go
- pkg/engine/runtime/terraform/terraform_runtime.go
- pkg/projectstack/types.go
- pkg/util/kube/config/config.go
- pkg/util/kube/config/config_test.go
/kind feature
This PR adds supports for setting kubeconfig file path in a stack dimension. 
Fixes #572 
```release-note
```
```docs
```
> feat: support setting kubeconfig in a stack dimension

- pkg/apis/secrets/types.go
- pkg/secrets/interface.go
/kind feature
add external secret store api and interface
Fixes #
```release-note
```
```docs
```
> feat: add external secret store api and interface

- pkg/apis/secrets/types.go
- pkg/secrets/interfaces.go
- pkg/secrets/providers.go
- pkg/secrets/providers_test.go
/kind feature
update secrets management related api typs and interfaces.
Fixes #
```release-note
```
```docs
```
> feat: update secrets related types and interfaces

- test/e2e/kusionctl_test.go
/kind test
This PR enables watch for `kusion apply` in e2e test. 
Fixes #619 
```release-note
```
```docs
```
> test: enable watch for kusion apply in e2e test

- pkg/modules/generators/workload/job_generator.go
/kind bug
fix job generator missing pod restartPolicy issue
Fixes #
```release-note
```
```docs
```
> fix: job generator missing pod restartPolicy issue

- test/e2e/kusionctl_test.go
Fixes #
```release-note
```
```docs
```
> fix: e2e tests

- pkg/apis/core/group.go
- pkg/apis/core/v1/intent.go
- pkg/apis/core/v1/types.go
- pkg/apis/core/v1/workspace.go
- pkg/apis/internal/group.go
- pkg/apis/internal/v1/types.go
re-pack basic api types for susitable code iteration
Fixes #
```release-note
```
```docs
```
> refactor: re-pack basic api types for susitable iteration

- pkg/apis/core/v1/workspace.go
- pkg/workspace/validation.go
- pkg/workspace/validation_test.go
/kind feature
update workspace api type add secret store config
Fixes #
```release-note
```
```docs
```
> feat: update workspace api type add secret store config

- .github/workflows/release.yaml
- .goreleaser_informal.yml
/kind feature
Update the latest version when releasing formal version.
> feat: update the latest version when releasing formal version

- pkg/secrets/interfaces.go
- pkg/secrets/providers.go
- pkg/secrets/providers/alicloud/secretsmanager/secretsmanager.go
- pkg/secrets/providers/alicloud/secretsmanager/secretsmanager_test.go
- pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
- pkg/secrets/providers/aws/secretsmanager/secretsmanager_test.go
- pkg/secrets/providers/azure/keyvault/keyvault.go
- pkg/secrets/providers/azure/keyvault/keyvault_test.go
- pkg/secrets/providers/hashivault/vault.go
- pkg/secrets/providers/hashivault/vault_test.go
- pkg/secrets/providers_test.go
refactor: rename SecretStoreFactory to SecretStoreProvider
Fixes #
```release-note
```
```docs
```
> refactor: rename SecretStoreFactory to SecretStoreProvider

- pkg/apis/core/v1/workspace.go
- pkg/secrets/interfaces.go
- pkg/secrets/providers/fake/fake.go
- pkg/secrets/providers/fake/fake_test.go
- pkg/secrets/providers/register/register.go
/kind feature
add fake secret store provider for testing
Fixes #
```release-note
```
```docs
```
> feat: add fake secret store provider for test

- pkg/modules/generators/app_configurations_generator.go
- pkg/modules/generators/workload/secret/secret_generator.go
- pkg/modules/generators/workload/secret/secret_generator_test.go
- pkg/modules/interfaces.go
secret generator add more test cases
Fixes #
```release-note
```
```docs
```
> chore: secret generator add more test cases

- pkg/modules/generators/workload/job_generator_test.go
- pkg/modules/generators/workload/network/ports_generator_test.go
- pkg/modules/generators/workload/service_generator_test.go
- pkg/modules/generators/workload/workload_generator_test.go
- pkg/workspace/util.go
- pkg/workspace/util_test.go
Fixes #
```release-note
```
```docs
```
> fix: map assert bug

- Dockerfile
- Dockerfile_kusionctl
Fixes #
```release-note
```
```docs
```
> chore: delete unused env KUSION_PATH

- pkg/modules/inputs/trait/ops_rule.go
Fixes #
```release-note
```
```docs
```
> docs: fix a maxunavailable bug

- docs/contributing.md
update contributing.md
Fixes #
```release-note
```
```docs
```
> docs: update contributing.md

- README-zh.md
- README.md
Fixes #
```release-note
```
```docs
```
> docs: update the readme

- commitlint.config.js
Fixes #
```release-note
```
```docs
```
> feat: allow commit body line longer than 100

- pkg/engine/operation/graph/resource_node.go
/kind bug
Fixes #
```release-note
```
```docs
```
> fix: inaccurate action type when a live resource has been deleted

- pkg/cmd/workspace/create/cmd.go
- pkg/cmd/workspace/del/cmd.go
- pkg/cmd/workspace/list/cmd.go
- pkg/cmd/workspace/show/cmd.go
- pkg/cmd/workspace/update/cmd.go
Fixes #
```release-note
```
```docs
```
> fix: delete the never-arriving return non-nil err

- pkg/modules/interfaces.go
Fixes #
```release-note
```
```docs
```
> chore: delete the redundant patcher interface

- .goreleaser.yml
Fixes #
```release-note
```
```docs
```
> feat: update goreleaser scoop, delete deprecated params

- pkg/apis/core/v1/config.go
Fixes #
```release-note
```
```docs
```
> feat: add config model

- pkg/apis/core/v1/config.go
Fixes #
```release-note
```
```docs
```
> feat: add specified structured backend config models

- pkg/modules/plugin.go
/kind feature
add kusion module plugin
Fixes #
```release-note
```
```docs
```
> feat: add kusion module plugin

- pkg/apis/core/v1/config.go
- pkg/config/validation/validation.go
- pkg/config/validation/validation_test.go
Fixes #
```release-note
```
```docs
```
> feat: add kusion config validation

- pkg/apis/core/v1/config.go
- pkg/config/opearator_test.go
- pkg/config/operator.go
- pkg/config/registry.go
- pkg/config/testdata/config_for_read.yaml
- pkg/config/testdata/config_invalid.yaml
- pkg/config/validation/validation.go
Fixes #
```release-note
```
```docs
```
> feat: add kusion config operator and support backend config operation

- pkg/config/operator.go
- pkg/config/util.go
- pkg/config/util_test.go
Fixes #
```release-note
```
```docs
```
> feat: add kusion config util functions

- pkg/config/operator.go
Fixes #
```release-note
```
```docs
```
> chore: fix golint-gocritic error

- pkg/apis/core/v1/appconfiguration.go
- pkg/modules/generators/app_configurations_generator.go
- pkg/modules/interfaces.go
- pkg/modules/plugin.go
Fixes #
```release-note
```
```docs
```
> feat: pass the workload when calling module grpc plugin

- docs/design/kusion_module/kusion_modules.md
- pkg/apis/core/v1/appconfiguration.go
- pkg/modules/proto/module.pb.go
- pkg/modules/proto/module.proto
Fixes #
```release-note
```
```docs
```
> docs: update module design doc generate interface definition

- pkg/modules/generators/app_configurations_generator.go
- pkg/modules/generators/app_configurations_generator_test.go
Fixes #
```release-note
```
```docs
```
> feat: support patching workload by resource patchers

- pkg/engine/state/storages/mysql.go
- pkg/engine/state/storages/mysql_test.go
- pkg/engine/state/storages/oss.go
- pkg/engine/state/storages/s3.go
Fixes #
```release-note
```
```docs
```
> style: make state storages more tidy

- go.mod
- go.sum
- pkg/cmd/config/cmd.go
- pkg/cmd/config/cmd_test.go
- pkg/cmd/config/get/cmd.go
- pkg/cmd/config/get/cmd_test.go
- pkg/cmd/config/get/options.go
- pkg/cmd/config/get/options_test.go
- pkg/cmd/config/list/cmd.go
- pkg/cmd/config/list/cmd_test.go
- pkg/cmd/config/set/cmd.go
- pkg/cmd/config/set/cmd_test.go
- pkg/cmd/config/set/options.go
- pkg/cmd/config/set/options_test.go
- pkg/cmd/config/unset/cmd.go
- pkg/cmd/config/unset/cmd_test.go
- pkg/cmd/config/unset/options.go
- pkg/cmd/config/unset/options_test.go
- pkg/cmd/config/util/util.go
- pkg/cmd/config/util/util_test.go
- pkg/cmd/workspace/util/util_test.go
Fixes #
```release-note
```
```docs
```
> feat: add config cmd, including subcmds get,list,set,unset

- README-zh.md
- README.md
Fixes #
```release-note
```
```docs
```
> docs: update the slack invite link

- pkg/engine/runtime/terraform/install.go
/kind bug
This PR fixes a bug of installing Terraform CLI. 
Fixes #
```release-note
```
```docs
```
> fix: fix a bug for terraform installation

- Makefile
Ref: https://github.com/bytedance/mockey?tab=readme-ov-file#error-function-is-too-short-to-patch
Fixes #
```release-note
```
```docs
```
> chore: disable go test optimization for the mock framework limitation

- go.mod
- go.sum
- pkg/cmd/mod/mod_push.go
/kind feature
build generator support darwin/arm64
Fixes #
```release-note
```
```docs
```
> feat: build generator support darwin/arm64

- pkg/cmd/mod/mod_push.go
/kind feature
This PR updates the module package structure for `kusion mod push` cmd. 
Fixes #
```release-note
```
```docs
```
> feat: update module structure for mod push

- pkg/cmd/generate/generator/generator.go
- pkg/cmd/mod/mod_push.go
- pkg/util/io/dir.go
- pkg/util/io/file.go
/kind feature
mod push add example dir also mark generator executable
Fixes #
```release-note
```
```docs
```
> feat: mod push add examples dir also mark generator executable

- pkg/util/io/dir.go
Fixes #
```release-note
```
```docs
```
> fix: module filename issue

- docs/design/kusion_module/kusion_modules.md
- pkg/apis/core/v1/appconfiguration.go
Fixes #
```release-note
```
```docs
```
> docs: update the module design doc

- pkg/scaffold/quickstart/dev/kcl.mod
- pkg/scaffold/quickstart/dev/main.k
/kind feature
This PR updates the `quickstart` demo for Kusion Module adaptation. 
Fixes #
```release-note
```
```docs
```
> feat: update quickstart demo for module adaptation

- pkg/cmd/build/util.go
- pkg/cmd/init/init.go
- pkg/engine/runtime/terraform/install.go
- test/e2e/kusionctl_test.go
/kind bug
This PR fixes some bugs, including some typos and wrong hints of the cmd. 
Fixes #
```release-note
```
```docs
```
> fix: some bugs

- pkg/cmd/mod/mod_push.go
Fixes #
```release-note
```
```docs
```
> feat: auto base64 user's token in mod push

- pkg/cmd/generate/generate.go
- pkg/cmd/mod/mod_push.go
Fixes #
```release-note
```
```docs
```
> feat: handle panic in cmd mod push and generate

- pkg/cmd/mod/mod_push.go
Fixes #
```release-note
```
```docs
```
> docs: update mod push examples

- pkg/cmd/generate/generate.go
- pkg/cmd/mod/mod_push.go
Fixes #
```release-note
```
```docs
```
> feat: expose err msg to stdout in generate and mod push

- pkg/modules/plugin.go
Fixes #
```release-note
```
```docs
```
> chore: fix typo module comments

- test/e2e/kusionctl_test.go
Fixes #
```release-note
```
```docs
```
> fix: uncomment e2e tests

- README-zh.md
- README.md
Fixes #
```release-note
```
```docs
```
> docs: rephrase readme

- go.mod
- go.sum
- pkg/util/io/dir.go
Fixes #
```release-note
```
```docs
```
> fix: illegal module content filename

- pkg/modules/plugin.go
Fixes #
```release-note
```
```docs
```
> fix: add module ".exe" suffix in Windows

- pkg/cmd/apply/options.go
- pkg/cmd/apply/options_test.go
- pkg/cmd/build/builders/doc.go
- pkg/cmd/generate/generate.go
- pkg/cmd/generate/generator/generator.go
- pkg/cmd/preview/options.go
- pkg/cmd/preview/options_test.go
/kind feature
update generate cmd behavior according to latest discussion
Fixes #
```release-note
```
```docs
```
> feat: adjust generate cmd behavior according to latest discussion

- pkg/apis/api.kusion.io/group.go
- pkg/apis/api.kusion.io/v1/resource.go
- pkg/apis/api.kusion.io/v1/types.go
/kind feature
add Extension api types
Fixes #
```release-note
```
```docs
```
> feat: add Extension api types

- pkg/cmd/mod/mod_push.go
Fixes #
```release-note
```
```docs
```
> feat: add version tags to the image and image index

- go.mod
- go.sum
- pkg/clipath/home.go
- pkg/clipath/home_unix_test.go
- pkg/clipath/home_windows_test.go
- pkg/clipath/lazypath.go
- pkg/clipath/lazypath_darwin_test.go
- pkg/clipath/lazypath_unix_test.go
- pkg/clipath/lazypath_windows_test.go
- pkg/util/kfile/file.go
- pkg/util/kfile/file_test.go
- pkg/util/pathutil/pathutil.go
- pkg/util/pathutil/pathutil_plan9.go
- pkg/util/pathutil/pathutil_test.go
- pkg/util/pathutil/pathutil_unix.go
- pkg/util/pathutil/pathutil_windows.go
update kfile to use lazy path
Fixes #
```release-note
```
```docs
```
> feat: add clipath and pathutil pkg to calculate filesystem paths

- pkg/cmd/project/create/options.go
- pkg/cmd/stack/create/options.go
/kind feature
This PR updates the implementation of `kusion project create` and `kusion stack create`, adding a hint when project and stack successfully created. 
Fixes #
```release-note
```
```docs
```
> feat: update kusion project and stack create

- pkg/apis/api.kusion.io/v1/types.go
- pkg/cmd/workspace/util/testdata/valid_ws.yaml
- pkg/modules/generators/app_configurations_generator_test.go
- pkg/workspace/storages/local_test.go
- pkg/workspace/storages/testdata/for_delete_workspaces/dev.yaml
- pkg/workspace/storages/testdata/for_set_current_workspaces/dev.yaml
- pkg/workspace/storages/testdata/workspaces/dev.yaml
- pkg/workspace/storages/testdata/workspaces/prod.yaml
- pkg/workspace/util.go
- pkg/workspace/util_test.go
- pkg/workspace/validation.go
- pkg/workspace/validation_test.go
This reverts commit ba43927e8d49e5d50c6ddc6f4d7c2238ee576d46. We'll move this commit to the next version
Fixes #
```release-note
```
```docs
```
> fix: Revert "feat: add configs in the workspace mod definition (#1066)"

- pkg/cmd/mod/mod_push.go
- pkg/engine/api/generate/generator/generator.go
- test/e2e/kusionctl_test.go
/kind feature
Fixes #
```release-note
```
```docs
```
> feat: move module binary to KUSION_HOME by new path format

- README-zh.md
- README.md
- docs/design/kusion_module/kusion_modules.md
Fixes #
```release-note
```
```docs
```
> fix: broken links in the readme

- pkg/cmd/workspace/update/options.go
Fixes #
```release-note
```
```docs
```
> fix: the bug of workspace update without name

- pkg/cmd/cmd.go
/kind feature
This PR removes the `kusion server` sub cmd from the root kusion cmd for `v0.11.1` release. 
Fixes #
```release-note
```
```docs
```
> feat: remove server from root cmd

- pkg/engine/release/storage.go
Fixes #
```release-note
```
```docs
```
> feat: add the release storage interface

- pkg/engine/state/storages/util.go
- pkg/workspace/storages/util.go
Fixes #
```release-note
```
```docs
```
> chore: clean up the exposing of mysql table

- pkg/engine/release/storage.go
- pkg/engine/release/storages/local.go
- pkg/engine/release/storages/local_test.go
- pkg/engine/release/storages/oss.go
- pkg/engine/release/storages/oss_test.go
- pkg/engine/release/storages/s3.go
- pkg/engine/release/storages/s3_test.go
- pkg/engine/release/storages/testdata/invalid_releases/test_project/test_ws/.metadata.yml
- pkg/engine/release/storages/testdata/releases/test_project/test_ws/.metadata.yml
- pkg/engine/release/storages/testdata/releases/test_project/test_ws/1.yaml
- pkg/engine/release/storages/testdata/releases/test_project/test_ws/2.yaml
- pkg/engine/release/storages/testdata/releases/test_project/test_ws/3.yaml
- pkg/engine/release/storages/util.go
- pkg/engine/release/storages/util_test.go
Fixes #
```release-note
```
```docs
```
> feat: realize release storage of local, oss and s3

- pkg/backend/backend.go
- pkg/backend/storages/local.go
- pkg/backend/storages/local_test.go
- pkg/backend/storages/oss.go
- pkg/backend/storages/oss_test.go
- pkg/backend/storages/s3.go
- pkg/backend/storages/s3_test.go
Fixes #
```release-note
```
```docs
```
> feat: realize release storage using backend

- pkg/engine/api/generate/generator/generator.go
Fixes #
```release-note
```
```docs
```
> feat: ignore built-in workloads during generating the Spec

- pkg/secrets/providers/aws/secretsmanager/secretsmanager.go
Fixes #
```release-note
```
```docs
```
> chore: delete redundant print msg

- pkg/cmd/mod/list.go
Fixes #
```release-note
```
```docs
```
> fix: delete an empty line in mod list

- pkg/cmd/mod/push.go
/kind bug
This PR fixes a bug of os arch option for `kusion mod push`. 
Fixes #
```release-note
```
```docs
```
> fix: os arch option for mod push

- README.md
Fixes #
```release-note
```
```docs
```
> fix: broken link of README.md

- README.md
Fixes #
```release-note
```
```docs
```
> fix: broken slack link of README.md

- pkg/engine/runtime/terraform/terraform_runtime.go
Fixes #
```release-note
```
```docs
```
> fix: invalid dir when deleting tf resources

- test/e2e/kusionctl_test.go
Fixes #
```release-note
```
```docs
```
> test: uncomment e2e tests

- README-zh.md
- README.md
Fixes #
```release-note
```
```docs
```
> docs: update the Chinese readme and the Windows download command

- pkg/engine/operation/graph/resource_node.go
- pkg/engine/operation/preview.go
Fixes #
```release-note
```
```docs
```
> feat: replace secret references in the preview

- pkg/cmd/preview/preview.go
- pkg/util/diff/diff.go
- pkg/util/diff/diff_test.go
/kind feature
This PR masks the sensitive data before printing the preview changes. 
Fixes #
```release-note
```
```docs
```
> feat: mask sensitive data before printing the preview changes

- pkg/cmd/preview/preview.go
/kind feature
This PR implements the support for `--all` flag of `kusion preview` to directly showcase all of the diff details. 
Fixes #
```release-note
```
```docs
```
> feat: support preview all details with flag

- pkg/engine/runtime/kubernetes/kubeops/config.go
- pkg/engine/runtime/kubernetes/kubernetes_runtime.go
/kind bug
This PR fixes a bug of getting `kubeConfig` client. 
Fixes #
```release-note
```
```docs
```
> fix: a bug of getting kubeconfig client

- pkg/apis/api.kusion.io/v1/types.go
- pkg/engine/operation/graph/resource_node.go
- pkg/modules/generators/app_configurations_generator.go
/kind feature
This PR supports the `importedResources` field in `Workspace` for importing the existing cloud resources. 
Fixes #1206 
```release-note
```
```docs
```
> feat: support imported resources

- pkg/modules/generators/app_configurations_generator.go
- pkg/modules/generators/secret/secret.go
Fixes #
```release-note
```
```docs
```
> feat: workload is no longer mandatory in the AppConfig

- go.mod
- pkg/modules/generators/app_configurations_generator.go
- pkg/modules/plugin.go
/kind feature
This PR sets the module plugin binary working directory when init the plugin. 
Fixes #
```release-note
```
```docs
```
> feat: set module plugin working dir

- .goreleaser.yml
- .goreleaser_informal.yml
/kind bug
This PR adds `tags=rpc` for builds in `.goreleaser.yml`. 
Fixes #
```release-note
```
```docs
```
> fix: add rpc tag for builds in goreleaser

- pkg/cmd/apply/apply.go
/kind bug
This PR fixes some bugs of watching while executing the `kusion apply` command. 
Fixes #1273 
```release-note
```
```docs
```
> fix: bugs of watching while apply

- pkg/cmd/cmd.go
- pkg/cmd/resource/resource.go
- pkg/cmd/resource/resource_test.go
Fixes #
```release-note
```
```docs
```
> feat: add resource sub command

- pkg/engine/runtime/kubernetes/kubernetes_runtime.go
Fixes #1277
```release-note
```
```docs
```
> fix: print all the resources during watch in scenarios involving multiple replicas

- pkg/backend/backend.go
- pkg/backend/storages/local.go
- pkg/backend/storages/oss.go
- pkg/backend/storages/s3.go
- pkg/cmd/project/cmd.go
- pkg/cmd/project/list/cmd.go
- pkg/cmd/project/list/cmd_test.go
- pkg/cmd/project/list/options.go
- pkg/cmd/project/list/options_test.go
- pkg/cmd/release/list_test.go
- pkg/cmd/release/show_test.go
- pkg/cmd/release/unlock_test.go
- pkg/cmd/workspace/list/options.go
- pkg/cmd/workspace/list/options_test.go
- pkg/project/storage.go
- pkg/project/storages/local.go
- pkg/project/storages/local_test.go
- pkg/project/storages/oss.go
- pkg/project/storages/oss_test.go
- pkg/project/storages/s3.go
- pkg/project/storages/s3_test.go
- pkg/project/storages/util.go
- pkg/project/storages/util_test.go
Fixes #
```release-note
```
```docs
```
> feat: add project list command

- pkg/cmd/project/list/cmd.go
- pkg/cmd/release/release.go
/kind cleanup
This PR refines the command descriptions for `kusion project list` and `kusion release`. 
Fixes #
```release-note
```
```docs
```
> chore: refine the command descriptions

- README.md
Fixes #
```release-note
```
```docs
```
> docs: update README.md to include OpenSSF Best Practice Badge

- api/openapispec/docs.go
- api/openapispec/swagger.json
- api/openapispec/swagger.yaml
- pkg/domain/constant/global.go
- pkg/domain/entity/resource.go
- pkg/infra/persistence/resource_model.go
- pkg/server/handler/resource/handler.go
- pkg/server/handler/resource/handler_test.go
- pkg/server/manager/stack/resource.go
- pkg/server/route/route.go
Fixes #
```release-note
```
```docs
```
> feat: add kusion resource graph api for server

- api/openapispec/docs.go
- api/openapispec/swagger.json
- api/openapispec/swagger.yaml
- pkg/domain/request/workspace_request.go
- pkg/server/handler/module/handler.go
- pkg/server/handler/workspace/configs.go
- pkg/server/handler/workspace/handler_test.go
- pkg/server/manager/workspace/configs.go
- pkg/server/manager/workspace/types.go
- pkg/server/manager/workspace/workspace_manager.go
- pkg/server/route/route.go
/kind feature
This PR adds the workspace config-related apis for kusion server. 
Fixes #
```release-note
```
```docs
```
> feat: add workspace config apis for kusion server

- pkg/domain/entity/resource.go
- pkg/domain/repository/repository.go
- pkg/engine/api/generate.go
- pkg/infra/persistence/project_model.go
- pkg/infra/persistence/resource.go
- pkg/infra/persistence/resource_model.go
- pkg/infra/persistence/resource_test.go
- pkg/server/manager/stack/execute.go
- pkg/server/manager/stack/resource.go
- pkg/server/manager/stack/resource_test.go
- pkg/server/manager/stack/util.go
Fixes #
```release-note
```
```docs
```
> Feat add resource ID validation and resource URN

- pkg/domain/entity/module.go
- pkg/domain/entity/run.go
- pkg/domain/entity/source.go
- pkg/domain/repository/repository.go
- pkg/infra/persistence/module.go
- pkg/infra/persistence/source.go
- pkg/infra/persistence/source_test.go
- pkg/infra/persistence/util.go
- pkg/infra/persistence/util_test.go
- pkg/server/handler/module/handler.go
- pkg/server/handler/source/handler.go
- pkg/server/handler/stack/run.go
- pkg/server/manager/module/module_manager.go
- pkg/server/manager/project/project_manager_test.go
- pkg/server/manager/source/source_manager.go
- pkg/server/manager/stack/util.go
Fixes #
```release-note
```
```docs
```
> feat: add filters for list sources, modules and runs APIs

- pkg/server/handler/stack/execute.go
- pkg/server/handler/stack/execute_async.go
Fixes #
```release-note
```
```docs
```
> fix: import v1 package for swagger doc generation

- pkg/server/handler/backend/handler.go
- pkg/server/handler/module/handler.go
- pkg/server/handler/organization/handler.go
- pkg/server/handler/project/handler.go
- pkg/server/handler/resource/handler.go
- pkg/server/handler/source/handler.go
- pkg/server/handler/stack/execute.go
- pkg/server/handler/stack/execute_async.go
- pkg/server/handler/stack/handler.go
- pkg/server/handler/stack/run.go
- pkg/server/handler/workspace/handler.go
Fixes #1342
```release-note
```
```docs
```
> fix: swagger doc generated response

- api/openapispec/docs.go
- api/openapispec/swagger.json
- api/openapispec/swagger.yaml
- pkg/cmd/server/database_access.go
- pkg/infra/persistence/module_model.go
- pkg/infra/persistence/resource.go
- pkg/server/handler/resource/handler.go
- pkg/server/handler/resource/handler_test.go
- pkg/server/handler/stack/run.go
- pkg/server/manager/module/module_manager.go
- pkg/server/manager/resource/util.go
Fixes #
```release-note
```
```docs
```
> fix: modules and runs api

- pkg/generators/appconfiguration/app_configurations_generator.go
/kind bug
This PR fixes a bug for removal environment variable patcher. 
Fixes #
```release-note
```
```docs
```
> fix: removal env patcher

- pkg/server/manager/project/project_manager.go
- pkg/server/manager/project/types.go
- pkg/server/manager/project/util.go
Fixes #
```release-note
```
```docs
```
> fix: missing default source name

- api/openapispec/docs.go
- api/openapispec/swagger.json
- api/openapispec/swagger.yaml
- pkg/infra/persistence/resource.go
- pkg/infra/persistence/resource_test.go
- pkg/server/handler/stack/execute_async.go
Fixes #
```release-note
```
```docs
```
> fix: correct naming

- pkg/infra/persistence/run_model.go
- pkg/infra/persistence/run_test.go
- pkg/server/handler/stack/execute_async.go
- pkg/server/handler/stack/utils.go
- pkg/server/manager/stack/execute.go
- pkg/server/manager/stack/types.go
- pkg/server/manager/stack/util.go
Fixes #
```release-note
```
```docs
```
> fix: npe when default backend is not set

- .github/workflows/release.yaml
- Dockerfile
- go.mod
- go.sum
/kind dependencies
This PR updates `Dockerfile` and bumps `kpm` pkg version to `v0.9.9`. 
Fixes #
```release-note
```
```docs
```
> chore: update dockerfile and bump kpm pkg version

- ui/src/components/kusionTabs/index.tsx
- ui/src/components/kusionTabs/styles.module.less
- ui/src/pages/modules/component/moduleForm/index.tsx
- ui/src/pages/modules/index.tsx
- ui/src/pages/projects/components/runs/generateDetail/index.tsx
- ui/src/pages/projects/components/runs/index.tsx
- ui/src/pages/projects/components/runs/previewDetail/index.tsx
- ui/src/pages/projects/index.tsx
- ui/src/pages/projects/projectDetail/index.tsx
- ui/src/pages/sources/index.tsx
- ui/src/pages/workspaces/components/workspaceCard/index.tsx
- ui/src/pages/workspaces/components/workspaceCard/styles.module.less
- ui/src/pages/workspaces/index.tsx
Fixes #
```release-note
```
```docs
```
> perf: runs logs pretty

- ui/src/pages/workspaces/components/workspaceCard/index.tsx
- ui/src/pages/workspaces/components/workspaceCard/styles.module.less
Fixes #
```release-note
```
```docs
```
> style: update workspace card hover effects

- pkg/engine/api/generate.go
- pkg/server/handler/stack/utils.go
Fixes #
```release-note
```
```docs
```
> fix: terraform resource provider validation rules

- pkg/domain/constant/resource.go
- pkg/server/manager/stack/util.go
Fixes #
```release-note
```
```docs
```
> fix: terraform empty resource name and type for hashicorp resources

- README.md
Fixes #
```release-note
```
```docs
```
> docs: add product hunt badge

- README.md
Fixes #
```release-note
```
```docs
```
> docs: update README to include demo video

- README.md
Fixes #
```release-note
```
```docs
```
> chore: Update demo video

- README.md
Fixes #
```release-note
```
```docs
```
> docs: update README.md to include kusion server installation note

- .github/workflows/e2e-test.yml
- mlc_config.json
/kind bug
Some github actions keep failing:
- E2e test fails, since ubuntu 20.04 is no logger supported. 👀https://github.com/actions/runner-images/issues/11101
- GitHub Action is unable to verify the existence of https://x.com/Kusionstack, so we will skip the link validity check for x.com.
Fixes #
```release-note
```
```docs
```
> fix: fix failed github actions

- .github/workflows/e2e-test.yml
Fixes #
```release-note
```
```docs
```
> chore: add cron e2e-test

- .github/workflows/check-md-links.yaml
- .github/workflows/mlc_config.json
- mlc_config.json
Fixes #
```release-note
```
```docs
```
> chore: retry link check on 429

- Makefile
/kind cleanup
Fixes #1437
```release-note
NONE
```
```docs
```
> fix: use --timeout in place of deprecated --deadline for golangci-lint
